/****************************************************************************
 *     Copyright (c) 1999-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Dec 30 03:07:12 2015
 *                 Full Compile MD5 Checksum  7bae0331743432ff949ccaf2024f4504
 *                     (minus title and desc)
 *                 MD5 Checksum               53e51220057dd4c33187ad494aa1a6d3
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     611
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
 ***************************************************************************/

#ifndef BCHP_MIB0_UNI3_H__
#define BCHP_MIB0_UNI3_H__

/***************************************************************************
 *MIB0_UNI3 - MIB Registers
 ***************************************************************************/
#define BCHP_MIB0_UNI3_GRFCS                     0x00400c00 /* [RW] Receive FCS Error Counter */
#define BCHP_MIB0_UNI3_GRXCF                     0x00400c04 /* [RW] Receive Control Frame Packet Counter */
#define BCHP_MIB0_UNI3_GRXPF                     0x00400c08 /* [RW] Receive Pause Frame Packet Counter */
#define BCHP_MIB0_UNI3_GRXUO                     0x00400c0c /* [RW] Receive Unknown OP Code Packet Counter */
#define BCHP_MIB0_UNI3_GRALN                     0x00400c10 /* [RW] Receive Alignmenet Error Counter */
#define BCHP_MIB0_UNI3_GRFLR                     0x00400c14 /* [RW] Receive Frame Length Out Of Range Counter */
#define BCHP_MIB0_UNI3_GRCDE                     0x00400c18 /* [RW] Receive Code Error Packet Counter */
#define BCHP_MIB0_UNI3_GRFCR                     0x00400c1c /* [RW] Receive Carrier Sense Error Packet Counter */
#define BCHP_MIB0_UNI3_GROVR                     0x00400c20 /* [RW] Receive Oversize Packet Counter */
#define BCHP_MIB0_UNI3_GRJBR                     0x00400c24 /* [RW] Receive Jabber Counter */
#define BCHP_MIB0_UNI3_GRMTUE                    0x00400c28 /* [RW] Receive MTU Error Packet Counter */
#define BCHP_MIB0_UNI3_RRPKT                     0x00400c2c /* [RW] Receive RUNT Packet Counter */
#define BCHP_MIB0_UNI3_RRUND                     0x00400c30 /* [RW] Receive RUNT Packet And Contain A Valid FCS */
#define BCHP_MIB0_UNI3_RRFRG                     0x00400c34 /* [RW] Receive RUNT Packet And Contain Invalid FCS or Alignment Error */
#define BCHP_MIB0_UNI3_RRBYT                     0x00400c38 /* [RW] Receive RUNT Packet Byte Counter */
#define BCHP_MIB0_UNI3_GRMCA                     0x00400c3c /* [RW] Receive Multicast Frame Counter */
#define BCHP_MIB0_UNI3_GRBCA                     0x00400c40 /* [RW] Receive Broadcast Frame Counter */
#define BCHP_MIB0_UNI3_GR64                      0x00400c44 /* [RW] Receive 64B Frame Counter */
#define BCHP_MIB0_UNI3_GR127                     0x00400c48 /* [RW] Receive 65B to 127B Frame Counter */
#define BCHP_MIB0_UNI3_GR255                     0x00400c4c /* [RW] Receive 128B to 255B Frame Counter */
#define BCHP_MIB0_UNI3_GR511                     0x00400c50 /* [RW] Receive 256B to 511B Frame Counter */
#define BCHP_MIB0_UNI3_GR1023                    0x00400c54 /* [RW] Receive 512B to 1023B Frame Counter */
#define BCHP_MIB0_UNI3_GR1518                    0x00400c58 /* [RW] Receive 1024B to 1518B Frame Counter */
#define BCHP_MIB0_UNI3_GRMGV                     0x00400c5c /* [RW] Receive 1519B to 1522B Good VLAN Frame Counter */
#define BCHP_MIB0_UNI3_GR2047                    0x00400c60 /* [RW] Receive 1522B to 2047B Frame Counter */
#define BCHP_MIB0_UNI3_GR4095                    0x00400c64 /* [RW] Receive 2048B to 4095B Frame Counter */
#define BCHP_MIB0_UNI3_GR9216                    0x00400c68 /* [RW] Receive 4096B to 9216B Frame Counter */
#define BCHP_MIB0_UNI3_GRPKT                     0x00400c6c /* [RW] Receive Packet Counter */
#define BCHP_MIB0_UNI3_GRBYT                     0x00400c70 /* [RW] Receive Byte Counter */
#define BCHP_MIB0_UNI3_GRUC                      0x00400c74 /* [RW] Receive Unicast Packet Counter */
#define BCHP_MIB0_UNI3_GRPOK                     0x00400c78 /* [RW] Receive Good Packet Counter */
#define BCHP_MIB0_UNI3_GRPPP                     0x00400c7c /* [RW] Receive PPP Packet Counter */
#define BCHP_MIB0_UNI3_GRCRC                     0x00400c80 /* [RW] Receive CRC Match Packet Counter */
#define BCHP_MIB0_UNI3_GTXPF                     0x00400c84 /* [RW] Transmit Pause Frame Packet Counter */
#define BCHP_MIB0_UNI3_GTJBR                     0x00400c88 /* [RW] Transmit Jabber Counter */
#define BCHP_MIB0_UNI3_GTFCS                     0x00400c8c /* [RW] Transmit FCS Error Counter */
#define BCHP_MIB0_UNI3_GTXCF                     0x00400c90 /* [RW] Transmit Control Frame Packet Counter */
#define BCHP_MIB0_UNI3_GTOVR                     0x00400c94 /* [RW] Transmit Oversize Packet Counter */
#define BCHP_MIB0_UNI3_GTDRF                     0x00400c98 /* [RW] Transmit Deferral Packet Counter */
#define BCHP_MIB0_UNI3_GTEDF                     0x00400c9c /* [RW] Transmit Excessive Deferral Packet Counter */
#define BCHP_MIB0_UNI3_GTSCL                     0x00400ca0 /* [RW] Transmit Single Collision Packet Counter */
#define BCHP_MIB0_UNI3_GTMCL                     0x00400ca4 /* [RW] Transmit Multiple Collision Packet Counter */
#define BCHP_MIB0_UNI3_GTLCL                     0x00400ca8 /* [RW] Transmit Late Collision Packet Counter */
#define BCHP_MIB0_UNI3_GTXCL                     0x00400cac /* [RW] Transmit Excessive Collision Packet Counter */
#define BCHP_MIB0_UNI3_GTFRG                     0x00400cb0 /* [RW] Transmit Fragments Packet Counter */
#define BCHP_MIB0_UNI3_GTNCL                     0x00400cb4 /* [RW] Transmit Total Collision Counter */
#define BCHP_MIB0_UNI3_GTMCA                     0x00400cb8 /* [RW] Transmit Multicast Packet Counter */
#define BCHP_MIB0_UNI3_GTBCA                     0x00400cbc /* [RW] Transmit Broadcast Packet Counter */
#define BCHP_MIB0_UNI3_TR64                      0x00400cc0 /* [RW] Transmit 64B Frame Counter */
#define BCHP_MIB0_UNI3_TR127                     0x00400cc4 /* [RW] Transmit 65B to 127B Frame Counter */
#define BCHP_MIB0_UNI3_TR255                     0x00400cc8 /* [RW] Transmit 128B to 255B Frame Counter */
#define BCHP_MIB0_UNI3_TR511                     0x00400ccc /* [RW] Transmit 256B to 511B Frame Counter */
#define BCHP_MIB0_UNI3_TR1023                    0x00400cd0 /* [RW] Transmit 512B to 1023B Frame Counter */
#define BCHP_MIB0_UNI3_TR1518                    0x00400cd4 /* [RW] Transmit 1024B to 1518B Frame Counter */
#define BCHP_MIB0_UNI3_TRMGV                     0x00400cd8 /* [RW] Transmit 1519B to 1522B Good VLAN Frame Counter */
#define BCHP_MIB0_UNI3_TR2047                    0x00400cdc /* [RW] Transmit 1522B to 2047B Frame Counter */
#define BCHP_MIB0_UNI3_TR4095                    0x00400ce0 /* [RW] Transmit 2048B to 4095B Frame Counter */
#define BCHP_MIB0_UNI3_TR9216                    0x00400ce4 /* [RW] Transmit 4096B to 9216B Frame Counter */
#define BCHP_MIB0_UNI3_GTPKT                     0x00400ce8 /* [RW] Transmit Packet Counter */
#define BCHP_MIB0_UNI3_GTBYT                     0x00400cec /* [RW] Transmit Byte Counter */
#define BCHP_MIB0_UNI3_GTUC                      0x00400cf0 /* [RW] Transmit Unicast Packet Counter */
#define BCHP_MIB0_UNI3_GTPOK                     0x00400cf4 /* [RW] Transmit Good Packet Counter */

/***************************************************************************
 *GRFCS - Receive FCS Error Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRFCS :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRFCS_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRFCS_RO_SHIFT                              0

/***************************************************************************
 *GRXCF - Receive Control Frame Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRXCF :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRXCF_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRXCF_RO_SHIFT                              0

/***************************************************************************
 *GRXPF - Receive Pause Frame Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRXPF :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRXPF_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRXPF_RO_SHIFT                              0

/***************************************************************************
 *GRXUO - Receive Unknown OP Code Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRXUO :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRXUO_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRXUO_RO_SHIFT                              0

/***************************************************************************
 *GRALN - Receive Alignmenet Error Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRALN :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRALN_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRALN_RO_SHIFT                              0

/***************************************************************************
 *GRFLR - Receive Frame Length Out Of Range Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRFLR :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRFLR_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRFLR_RO_SHIFT                              0

/***************************************************************************
 *GRCDE - Receive Code Error Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRCDE :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRCDE_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRCDE_RO_SHIFT                              0

/***************************************************************************
 *GRFCR - Receive Carrier Sense Error Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRFCR :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRFCR_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRFCR_RO_SHIFT                              0

/***************************************************************************
 *GROVR - Receive Oversize Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GROVR :: RO [31:00] */
#define BCHP_MIB0_UNI3_GROVR_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GROVR_RO_SHIFT                              0

/***************************************************************************
 *GRJBR - Receive Jabber Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRJBR :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRJBR_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRJBR_RO_SHIFT                              0

/***************************************************************************
 *GRMTUE - Receive MTU Error Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRMTUE :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRMTUE_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_GRMTUE_RO_SHIFT                             0

/***************************************************************************
 *RRPKT - Receive RUNT Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: RRPKT :: RO [31:00] */
#define BCHP_MIB0_UNI3_RRPKT_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_RRPKT_RO_SHIFT                              0

/***************************************************************************
 *RRUND - Receive RUNT Packet And Contain A Valid FCS
 ***************************************************************************/
/* MIB0_UNI3 :: RRUND :: RO [31:00] */
#define BCHP_MIB0_UNI3_RRUND_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_RRUND_RO_SHIFT                              0

/***************************************************************************
 *RRFRG - Receive RUNT Packet And Contain Invalid FCS or Alignment Error
 ***************************************************************************/
/* MIB0_UNI3 :: RRFRG :: RO [31:00] */
#define BCHP_MIB0_UNI3_RRFRG_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_RRFRG_RO_SHIFT                              0

/***************************************************************************
 *RRBYT - Receive RUNT Packet Byte Counter
 ***************************************************************************/
/* MIB0_UNI3 :: RRBYT :: RO [31:00] */
#define BCHP_MIB0_UNI3_RRBYT_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_RRBYT_RO_SHIFT                              0

/***************************************************************************
 *GRMCA - Receive Multicast Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRMCA :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRMCA_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRMCA_RO_SHIFT                              0

/***************************************************************************
 *GRBCA - Receive Broadcast Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRBCA :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRBCA_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRBCA_RO_SHIFT                              0

/***************************************************************************
 *GR64 - Receive 64B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR64 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR64_RO_MASK                                0xffffffff
#define BCHP_MIB0_UNI3_GR64_RO_SHIFT                               0

/***************************************************************************
 *GR127 - Receive 65B to 127B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR127 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR127_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GR127_RO_SHIFT                              0

/***************************************************************************
 *GR255 - Receive 128B to 255B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR255 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR255_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GR255_RO_SHIFT                              0

/***************************************************************************
 *GR511 - Receive 256B to 511B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR511 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR511_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GR511_RO_SHIFT                              0

/***************************************************************************
 *GR1023 - Receive 512B to 1023B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR1023 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR1023_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_GR1023_RO_SHIFT                             0

/***************************************************************************
 *GR1518 - Receive 1024B to 1518B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR1518 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR1518_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_GR1518_RO_SHIFT                             0

/***************************************************************************
 *GRMGV - Receive 1519B to 1522B Good VLAN Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRMGV :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRMGV_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRMGV_RO_SHIFT                              0

/***************************************************************************
 *GR2047 - Receive 1522B to 2047B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR2047 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR2047_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_GR2047_RO_SHIFT                             0

/***************************************************************************
 *GR4095 - Receive 2048B to 4095B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR4095 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR4095_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_GR4095_RO_SHIFT                             0

/***************************************************************************
 *GR9216 - Receive 4096B to 9216B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GR9216 :: RO [31:00] */
#define BCHP_MIB0_UNI3_GR9216_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_GR9216_RO_SHIFT                             0

/***************************************************************************
 *GRPKT - Receive Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRPKT :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRPKT_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRPKT_RO_SHIFT                              0

/***************************************************************************
 *GRBYT - Receive Byte Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRBYT :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRBYT_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRBYT_RO_SHIFT                              0

/***************************************************************************
 *GRUC - Receive Unicast Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRUC :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRUC_RO_MASK                                0xffffffff
#define BCHP_MIB0_UNI3_GRUC_RO_SHIFT                               0

/***************************************************************************
 *GRPOK - Receive Good Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRPOK :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRPOK_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRPOK_RO_SHIFT                              0

/***************************************************************************
 *GRPPP - Receive PPP Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRPPP :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRPPP_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRPPP_RO_SHIFT                              0

/***************************************************************************
 *GRCRC - Receive CRC Match Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GRCRC :: RO [31:00] */
#define BCHP_MIB0_UNI3_GRCRC_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GRCRC_RO_SHIFT                              0

/***************************************************************************
 *GTXPF - Transmit Pause Frame Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTXPF :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTXPF_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTXPF_RO_SHIFT                              0

/***************************************************************************
 *GTJBR - Transmit Jabber Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTJBR :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTJBR_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTJBR_RO_SHIFT                              0

/***************************************************************************
 *GTFCS - Transmit FCS Error Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTFCS :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTFCS_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTFCS_RO_SHIFT                              0

/***************************************************************************
 *GTXCF - Transmit Control Frame Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTXCF :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTXCF_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTXCF_RO_SHIFT                              0

/***************************************************************************
 *GTOVR - Transmit Oversize Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTOVR :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTOVR_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTOVR_RO_SHIFT                              0

/***************************************************************************
 *GTDRF - Transmit Deferral Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTDRF :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTDRF_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTDRF_RO_SHIFT                              0

/***************************************************************************
 *GTEDF - Transmit Excessive Deferral Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTEDF :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTEDF_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTEDF_RO_SHIFT                              0

/***************************************************************************
 *GTSCL - Transmit Single Collision Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTSCL :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTSCL_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTSCL_RO_SHIFT                              0

/***************************************************************************
 *GTMCL - Transmit Multiple Collision Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTMCL :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTMCL_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTMCL_RO_SHIFT                              0

/***************************************************************************
 *GTLCL - Transmit Late Collision Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTLCL :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTLCL_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTLCL_RO_SHIFT                              0

/***************************************************************************
 *GTXCL - Transmit Excessive Collision Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTXCL :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTXCL_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTXCL_RO_SHIFT                              0

/***************************************************************************
 *GTFRG - Transmit Fragments Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTFRG :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTFRG_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTFRG_RO_SHIFT                              0

/***************************************************************************
 *GTNCL - Transmit Total Collision Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTNCL :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTNCL_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTNCL_RO_SHIFT                              0

/***************************************************************************
 *GTMCA - Transmit Multicast Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTMCA :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTMCA_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTMCA_RO_SHIFT                              0

/***************************************************************************
 *GTBCA - Transmit Broadcast Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTBCA :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTBCA_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTBCA_RO_SHIFT                              0

/***************************************************************************
 *TR64 - Transmit 64B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR64 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR64_RO_MASK                                0xffffffff
#define BCHP_MIB0_UNI3_TR64_RO_SHIFT                               0

/***************************************************************************
 *TR127 - Transmit 65B to 127B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR127 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR127_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_TR127_RO_SHIFT                              0

/***************************************************************************
 *TR255 - Transmit 128B to 255B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR255 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR255_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_TR255_RO_SHIFT                              0

/***************************************************************************
 *TR511 - Transmit 256B to 511B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR511 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR511_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_TR511_RO_SHIFT                              0

/***************************************************************************
 *TR1023 - Transmit 512B to 1023B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR1023 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR1023_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_TR1023_RO_SHIFT                             0

/***************************************************************************
 *TR1518 - Transmit 1024B to 1518B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR1518 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR1518_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_TR1518_RO_SHIFT                             0

/***************************************************************************
 *TRMGV - Transmit 1519B to 1522B Good VLAN Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TRMGV :: RO [31:00] */
#define BCHP_MIB0_UNI3_TRMGV_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_TRMGV_RO_SHIFT                              0

/***************************************************************************
 *TR2047 - Transmit 1522B to 2047B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR2047 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR2047_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_TR2047_RO_SHIFT                             0

/***************************************************************************
 *TR4095 - Transmit 2048B to 4095B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR4095 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR4095_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_TR4095_RO_SHIFT                             0

/***************************************************************************
 *TR9216 - Transmit 4096B to 9216B Frame Counter
 ***************************************************************************/
/* MIB0_UNI3 :: TR9216 :: RO [31:00] */
#define BCHP_MIB0_UNI3_TR9216_RO_MASK                              0xffffffff
#define BCHP_MIB0_UNI3_TR9216_RO_SHIFT                             0

/***************************************************************************
 *GTPKT - Transmit Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTPKT :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTPKT_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTPKT_RO_SHIFT                              0

/***************************************************************************
 *GTBYT - Transmit Byte Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTBYT :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTBYT_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTBYT_RO_SHIFT                              0

/***************************************************************************
 *GTUC - Transmit Unicast Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTUC :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTUC_RO_MASK                                0xffffffff
#define BCHP_MIB0_UNI3_GTUC_RO_SHIFT                               0

/***************************************************************************
 *GTPOK - Transmit Good Packet Counter
 ***************************************************************************/
/* MIB0_UNI3 :: GTPOK :: RO [31:00] */
#define BCHP_MIB0_UNI3_GTPOK_RO_MASK                               0xffffffff
#define BCHP_MIB0_UNI3_GTPOK_RO_SHIFT                              0

#endif /* #ifndef BCHP_MIB0_UNI3_H__ */

/* End of File */
