/****************************************************************************
 *
 * Broadcom Proprietary and Confidential.
 * (c) 2017 Broadcom. All rights reserved.
 * The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * Unless you and Broadcom execute a separate written software license
 * agreement governing use of this software, this software is licensed to
 * you under the terms of the GNU General Public License version 2 (the
 * "GPL"), available at [http://www.broadcom.com/licenses/GPLv2.php], with
 * the following added to such license:
 *
 * As a special exception, the copyright holders of this software give you
 * permission to link this software with independent modules, and to copy
 * and distribute the resulting executable under terms of your choice,
 * provided that you also meet, for each linked independent module, the
 * terms and conditions of the license of that module. An independent
 * module is a module which is not derived from this software. The special
 * exception does not apply to any modifications of the software.
 *
 * Notwithstanding the above, under no circumstances may you combine this
 * software in any way with any other Broadcom software provided under a
 * license other than the GPL, without Broadcom's express prior written
 * consent.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Jun 10 03:09:36 2015
 *                 Full Compile MD5 Checksum  e8bde4108283f67d401938287dbb6bde
 *                     (minus title and desc)
 *                 MD5 Checksum               56f0f944fbd407545cd964e7b4e7f7b0
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_GPIO_PER_H__
#define BCHP_GPIO_PER_H__

/***************************************************************************
 *GPIO_PER - GPIO Block Control Registers
 ***************************************************************************/
#define BCHP_GPIO_PER_DIR_031_000                0x03c00500 /* [RW] GPIO[31:0] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_063_032                0x03c00504 /* [RW] GPIO[63:32] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_095_064                0x03c00508 /* [RW] GPIO[95:64] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_127_096                0x03c0050c /* [RW] GPIO[127:96] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_159_128                0x03c00510 /* [RW] GPIO[159:128] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_191_160                0x03c00514 /* [RW] GPIO[191:160] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_223_192                0x03c00518 /* [RW] GPIO[223:192] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_255_224                0x03c0051c /* [RW] GPIO[255:224] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_287_256                0x03c00520 /* [RW] GPIO[287:256] Pin Direction Control Register */
#define BCHP_GPIO_PER_DIR_319_288                0x03c00524 /* [RW] GPIO[319:288] Pin Direction Control Register */
#define BCHP_GPIO_PER_DATA_031_000               0x03c00528 /* [RW] GPIO[31:0] Pin Data Register */
#define BCHP_GPIO_PER_DATA_063_032               0x03c0052c /* [RW] GPIO[63:32] Pin Data Register */
#define BCHP_GPIO_PER_DATA_095_064               0x03c00530 /* [RW] GPIO[95:64] Pin Data Register */
#define BCHP_GPIO_PER_DATA_127_096               0x03c00534 /* [RW] GPIO[127:96] Pin Data Register */
#define BCHP_GPIO_PER_DATA_159_128               0x03c00538 /* [RW] GPIO[159:128] Pin Data Register */
#define BCHP_GPIO_PER_DATA_191_160               0x03c0053c /* [RW] GPIO[191:160] Pin Data Register */
#define BCHP_GPIO_PER_DATA_223_192               0x03c00540 /* [RW] GPIO[223:192] Pin Data Register */
#define BCHP_GPIO_PER_DATA_255_224               0x03c00544 /* [RW] GPIO[255:224] Pin Data Register */
#define BCHP_GPIO_PER_DATA_287_256               0x03c00548 /* [RW] GPIO[287:256] Pin Data Register */
#define BCHP_GPIO_PER_DATA_319_288               0x03c0054c /* [RW] GPIO[319:288] Pin Data Register */
#define BCHP_GPIO_PER_PAD_CTRL                   0x03c00550 /* [RW] GPIO RGMII PAD CTRL  Register */
#define BCHP_GPIO_PER_SPI_CONFIG                 0x03c00554 /* [RW] SPI Configuration Register */
#define BCHP_GPIO_PER_TESTCONTROL                0x03c00558 /* [RW] TESTCONTROL Register */
#define BCHP_GPIO_PER_TestPortBlkEnMsb           0x03c0055c /* [RW] Test Port Block Enable MSB */
#define BCHP_GPIO_PER_TestPortBlkEnLsb           0x03c00560 /* [RW] Test Port Block Enable LSB */
#define BCHP_GPIO_PER_TestPortBlkDataMsb         0x03c00564 /* [RW] Test Port Block Data MSB */
#define BCHP_GPIO_PER_TestPortBlkDataLsb         0x03c00568 /* [RW] Test Port Block Data LSB */
#define BCHP_GPIO_PER_TestPortCommand            0x03c0056c /* [RW] Test Port Command Register */
#define BCHP_GPIO_PER_diagReadBack               0x03c00570 /* [RO] Diagnostic Readback Register */
#define BCHP_GPIO_PER_diagReadBackHi             0x03c00574 /* [RO] Diagnostic High Readback Register */
#define BCHP_GPIO_PER_gpioReg                    0x03c00578 /* [RW] General Purpose Register */

/***************************************************************************
 *DIR_031_000 - GPIO[31:0] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_031_000 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_031_000_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_031_000_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_031_000_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_063_032 - GPIO[63:32] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_063_032 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_063_032_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_063_032_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_063_032_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_095_064 - GPIO[95:64] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_095_064 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_095_064_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_095_064_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_095_064_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_127_096 - GPIO[127:96] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_127_096 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_127_096_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_127_096_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_127_096_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_159_128 - GPIO[159:128] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_159_128 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_159_128_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_159_128_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_159_128_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_191_160 - GPIO[191:160] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_191_160 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_191_160_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_191_160_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_191_160_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_223_192 - GPIO[223:192] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_223_192 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_223_192_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_223_192_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_223_192_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_255_224 - GPIO[255:224] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_255_224 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_255_224_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_255_224_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_255_224_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_287_256 - GPIO[287:256] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_287_256 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_287_256_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_287_256_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_287_256_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DIR_319_288 - GPIO[319:288] Pin Direction Control Register
 ***************************************************************************/
/* GPIO_PER :: DIR_319_288 :: GPIO_oe [31:00] */
#define BCHP_GPIO_PER_DIR_319_288_GPIO_oe_MASK                     0xffffffff
#define BCHP_GPIO_PER_DIR_319_288_GPIO_oe_SHIFT                    0
#define BCHP_GPIO_PER_DIR_319_288_GPIO_oe_DEFAULT                  0x00000000

/***************************************************************************
 *DATA_031_000 - GPIO[31:0] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_031_000 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_031_000_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_031_000_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_031_000_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_063_032 - GPIO[63:32] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_063_032 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_063_032_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_063_032_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_063_032_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_095_064 - GPIO[95:64] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_095_064 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_095_064_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_095_064_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_095_064_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_127_096 - GPIO[127:96] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_127_096 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_127_096_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_127_096_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_127_096_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_159_128 - GPIO[159:128] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_159_128 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_159_128_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_159_128_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_159_128_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_191_160 - GPIO[191:160] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_191_160 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_191_160_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_191_160_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_191_160_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_223_192 - GPIO[223:192] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_223_192 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_223_192_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_223_192_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_223_192_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_255_224 - GPIO[255:224] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_255_224 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_255_224_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_255_224_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_255_224_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_287_256 - GPIO[287:256] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_287_256 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_287_256_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_287_256_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_287_256_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *DATA_319_288 - GPIO[319:288] Pin Data Register
 ***************************************************************************/
/* GPIO_PER :: DATA_319_288 :: GPIO_value [31:00] */
#define BCHP_GPIO_PER_DATA_319_288_GPIO_value_MASK                 0xffffffff
#define BCHP_GPIO_PER_DATA_319_288_GPIO_value_SHIFT                0
#define BCHP_GPIO_PER_DATA_319_288_GPIO_value_DEFAULT              0x00000000

/***************************************************************************
 *PAD_CTRL - GPIO RGMII PAD CTRL  Register
 ***************************************************************************/
/* GPIO_PER :: PAD_CTRL :: reserved0 [31:24] */
#define BCHP_GPIO_PER_PAD_CTRL_reserved0_MASK                      0xff000000
#define BCHP_GPIO_PER_PAD_CTRL_reserved0_SHIFT                     24

/* GPIO_PER :: PAD_CTRL :: pup_USB1_PWRFLT [23:23] */
#define BCHP_GPIO_PER_PAD_CTRL_pup_USB1_PWRFLT_MASK                0x00800000
#define BCHP_GPIO_PER_PAD_CTRL_pup_USB1_PWRFLT_SHIFT               23
#define BCHP_GPIO_PER_PAD_CTRL_pup_USB1_PWRFLT_DEFAULT             0x00000000

/* GPIO_PER :: PAD_CTRL :: pdn_USB1_PWRFLT [22:22] */
#define BCHP_GPIO_PER_PAD_CTRL_pdn_USB1_PWRFLT_MASK                0x00400000
#define BCHP_GPIO_PER_PAD_CTRL_pdn_USB1_PWRFLT_SHIFT               22
#define BCHP_GPIO_PER_PAD_CTRL_pdn_USB1_PWRFLT_DEFAULT             0x00000000

/* GPIO_PER :: PAD_CTRL :: ind_USB1_PWRFLT [21:21] */
#define BCHP_GPIO_PER_PAD_CTRL_ind_USB1_PWRFLT_MASK                0x00200000
#define BCHP_GPIO_PER_PAD_CTRL_ind_USB1_PWRFLT_SHIFT               21
#define BCHP_GPIO_PER_PAD_CTRL_ind_USB1_PWRFLT_DEFAULT             0x00000000

/* GPIO_PER :: PAD_CTRL :: hys_en_USB1_PWRFLT [20:20] */
#define BCHP_GPIO_PER_PAD_CTRL_hys_en_USB1_PWRFLT_MASK             0x00100000
#define BCHP_GPIO_PER_PAD_CTRL_hys_en_USB1_PWRFLT_SHIFT            20
#define BCHP_GPIO_PER_PAD_CTRL_hys_en_USB1_PWRFLT_DEFAULT          0x00000000

/* GPIO_PER :: PAD_CTRL :: pup_USB0_PWRFLT [19:19] */
#define BCHP_GPIO_PER_PAD_CTRL_pup_USB0_PWRFLT_MASK                0x00080000
#define BCHP_GPIO_PER_PAD_CTRL_pup_USB0_PWRFLT_SHIFT               19
#define BCHP_GPIO_PER_PAD_CTRL_pup_USB0_PWRFLT_DEFAULT             0x00000000

/* GPIO_PER :: PAD_CTRL :: pdn_USB0_PWRFLT [18:18] */
#define BCHP_GPIO_PER_PAD_CTRL_pdn_USB0_PWRFLT_MASK                0x00040000
#define BCHP_GPIO_PER_PAD_CTRL_pdn_USB0_PWRFLT_SHIFT               18
#define BCHP_GPIO_PER_PAD_CTRL_pdn_USB0_PWRFLT_DEFAULT             0x00000000

/* GPIO_PER :: PAD_CTRL :: ind_USB0_PWRFLT [17:17] */
#define BCHP_GPIO_PER_PAD_CTRL_ind_USB0_PWRFLT_MASK                0x00020000
#define BCHP_GPIO_PER_PAD_CTRL_ind_USB0_PWRFLT_SHIFT               17
#define BCHP_GPIO_PER_PAD_CTRL_ind_USB0_PWRFLT_DEFAULT             0x00000000

/* GPIO_PER :: PAD_CTRL :: hys_en_USB0_PWRFLT [16:16] */
#define BCHP_GPIO_PER_PAD_CTRL_hys_en_USB0_PWRFLT_MASK             0x00010000
#define BCHP_GPIO_PER_PAD_CTRL_hys_en_USB0_PWRFLT_SHIFT            16
#define BCHP_GPIO_PER_PAD_CTRL_hys_en_USB0_PWRFLT_DEFAULT          0x00000000

/* GPIO_PER :: PAD_CTRL :: reserved1 [15:11] */
#define BCHP_GPIO_PER_PAD_CTRL_reserved1_MASK                      0x0000f800
#define BCHP_GPIO_PER_PAD_CTRL_reserved1_SHIFT                     11

/* GPIO_PER :: PAD_CTRL :: rgmii_0_pad_amp_en [10:10] */
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_amp_en_MASK             0x00000400
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_amp_en_SHIFT            10
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_amp_en_DEFAULT          0x00000000

/* GPIO_PER :: PAD_CTRL :: rgmii_0_pad_sel_gmii [09:09] */
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_gmii_MASK           0x00000200
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_gmii_SHIFT          9
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_gmii_DEFAULT        0x00000001

/* GPIO_PER :: PAD_CTRL :: rgmii_0_pad_modehv [08:08] */
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_modehv_MASK             0x00000100
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_modehv_SHIFT            8
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_modehv_DEFAULT          0x00000001

/* GPIO_PER :: PAD_CTRL :: rgmii_0_pad_sel [07:05] */
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_MASK                0x000000e0
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_SHIFT               5
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DEFAULT             0x00000003
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_2MA           0
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_4MA           1
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_6MA           2
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_8MA           3
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_10MA          4
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_12MA          5
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_14MA          6
#define BCHP_GPIO_PER_PAD_CTRL_rgmii_0_pad_sel_DRIVE_16MA          7

/* GPIO_PER :: PAD_CTRL :: led_pad_control [04:04] */
#define BCHP_GPIO_PER_PAD_CTRL_led_pad_control_MASK                0x00000010
#define BCHP_GPIO_PER_PAD_CTRL_led_pad_control_SHIFT               4
#define BCHP_GPIO_PER_PAD_CTRL_led_pad_control_DEFAULT             0x00000000

/* GPIO_PER :: PAD_CTRL :: GPIO_pad_slew [03:03] */
#define BCHP_GPIO_PER_PAD_CTRL_GPIO_pad_slew_MASK                  0x00000008
#define BCHP_GPIO_PER_PAD_CTRL_GPIO_pad_slew_SHIFT                 3
#define BCHP_GPIO_PER_PAD_CTRL_GPIO_pad_slew_DEFAULT               0x00000001

/* GPIO_PER :: PAD_CTRL :: GPIO_pad_drvsel [02:00] */
#define BCHP_GPIO_PER_PAD_CTRL_GPIO_pad_drvsel_MASK                0x00000007
#define BCHP_GPIO_PER_PAD_CTRL_GPIO_pad_drvsel_SHIFT               0
#define BCHP_GPIO_PER_PAD_CTRL_GPIO_pad_drvsel_DEFAULT             0x00000005

/***************************************************************************
 *SPI_CONFIG - SPI Configuration Register
 ***************************************************************************/
/* GPIO_PER :: SPI_CONFIG :: reserved0 [31:18] */
#define BCHP_GPIO_PER_SPI_CONFIG_reserved0_MASK                    0xfffc0000
#define BCHP_GPIO_PER_SPI_CONFIG_reserved0_SHIFT                   18

/* GPIO_PER :: SPI_CONFIG :: SpiSSlv [17:17] */
#define BCHP_GPIO_PER_SPI_CONFIG_SpiSSlv_MASK                      0x00020000
#define BCHP_GPIO_PER_SPI_CONFIG_SpiSSlv_SHIFT                     17
#define BCHP_GPIO_PER_SPI_CONFIG_SpiSSlv_DEFAULT                   0x00000000

/* GPIO_PER :: SPI_CONFIG :: SpiSlvRst [16:16] */
#define BCHP_GPIO_PER_SPI_CONFIG_SpiSlvRst_MASK                    0x00010000
#define BCHP_GPIO_PER_SPI_CONFIG_SpiSlvRst_SHIFT                   16
#define BCHP_GPIO_PER_SPI_CONFIG_SpiSlvRst_DEFAULT                 0x00000000

/* GPIO_PER :: SPI_CONFIG :: reserved1 [15:05] */
#define BCHP_GPIO_PER_SPI_CONFIG_reserved1_MASK                    0x0000ffe0
#define BCHP_GPIO_PER_SPI_CONFIG_reserved1_SHIFT                   5

/* GPIO_PER :: SPI_CONFIG :: Serial_AddrCfg [04:01] */
#define BCHP_GPIO_PER_SPI_CONFIG_Serial_AddrCfg_MASK               0x0000001e
#define BCHP_GPIO_PER_SPI_CONFIG_Serial_AddrCfg_SHIFT              1
#define BCHP_GPIO_PER_SPI_CONFIG_Serial_AddrCfg_DEFAULT            0x00000004

/* GPIO_PER :: SPI_CONFIG :: reserved2 [00:00] */
#define BCHP_GPIO_PER_SPI_CONFIG_reserved2_MASK                    0x00000001
#define BCHP_GPIO_PER_SPI_CONFIG_reserved2_SHIFT                   0

/***************************************************************************
 *TESTCONTROL - TESTCONTROL Register
 ***************************************************************************/
/* GPIO_PER :: TESTCONTROL :: SpiOverride [31:31] */
#define BCHP_GPIO_PER_TESTCONTROL_SpiOverride_MASK                 0x80000000
#define BCHP_GPIO_PER_TESTCONTROL_SpiOverride_SHIFT                31
#define BCHP_GPIO_PER_TESTCONTROL_SpiOverride_DEFAULT              0x00000000

/* GPIO_PER :: TESTCONTROL :: reserved0 [30:11] */
#define BCHP_GPIO_PER_TESTCONTROL_reserved0_MASK                   0x7ffff800
#define BCHP_GPIO_PER_TESTCONTROL_reserved0_SHIFT                  11

/* GPIO_PER :: TESTCONTROL :: TEST_EN [10:10] */
#define BCHP_GPIO_PER_TESTCONTROL_TEST_EN_MASK                     0x00000400
#define BCHP_GPIO_PER_TESTCONTROL_TEST_EN_SHIFT                    10
#define BCHP_GPIO_PER_TESTCONTROL_TEST_EN_DEFAULT                  0x00000000

/* GPIO_PER :: TESTCONTROL :: TEST_MODE [09:00] */
#define BCHP_GPIO_PER_TESTCONTROL_TEST_MODE_MASK                   0x000003ff
#define BCHP_GPIO_PER_TESTCONTROL_TEST_MODE_SHIFT                  0
#define BCHP_GPIO_PER_TESTCONTROL_TEST_MODE_DEFAULT                0x00000000

/***************************************************************************
 *TestPortBlkEnMsb - Test Port Block Enable MSB
 ***************************************************************************/
/* GPIO_PER :: TestPortBlkEnMsb :: TP_BLK_EN_MSB [31:00] */
#define BCHP_GPIO_PER_TestPortBlkEnMsb_TP_BLK_EN_MSB_MASK          0xffffffff
#define BCHP_GPIO_PER_TestPortBlkEnMsb_TP_BLK_EN_MSB_SHIFT         0
#define BCHP_GPIO_PER_TestPortBlkEnMsb_TP_BLK_EN_MSB_DEFAULT       0x00000000

/***************************************************************************
 *TestPortBlkEnLsb - Test Port Block Enable LSB
 ***************************************************************************/
/* GPIO_PER :: TestPortBlkEnLsb :: TP_BLK_EN_LSB [31:00] */
#define BCHP_GPIO_PER_TestPortBlkEnLsb_TP_BLK_EN_LSB_MASK          0xffffffff
#define BCHP_GPIO_PER_TestPortBlkEnLsb_TP_BLK_EN_LSB_SHIFT         0
#define BCHP_GPIO_PER_TestPortBlkEnLsb_TP_BLK_EN_LSB_DEFAULT       0x00000000

/***************************************************************************
 *TestPortBlkDataMsb - Test Port Block Data MSB
 ***************************************************************************/
/* GPIO_PER :: TestPortBlkDataMsb :: TP_BLK_DATA_MSB [31:00] */
#define BCHP_GPIO_PER_TestPortBlkDataMsb_TP_BLK_DATA_MSB_MASK      0xffffffff
#define BCHP_GPIO_PER_TestPortBlkDataMsb_TP_BLK_DATA_MSB_SHIFT     0
#define BCHP_GPIO_PER_TestPortBlkDataMsb_TP_BLK_DATA_MSB_DEFAULT   0x00000000

/***************************************************************************
 *TestPortBlkDataLsb - Test Port Block Data LSB
 ***************************************************************************/
/* GPIO_PER :: TestPortBlkDataLsb :: TP_BLK_DATA_LSB [31:00] */
#define BCHP_GPIO_PER_TestPortBlkDataLsb_TP_BLK_DATA_LSB_MASK      0xffffffff
#define BCHP_GPIO_PER_TestPortBlkDataLsb_TP_BLK_DATA_LSB_SHIFT     0
#define BCHP_GPIO_PER_TestPortBlkDataLsb_TP_BLK_DATA_LSB_DEFAULT   0x00000000

/***************************************************************************
 *TestPortCommand - Test Port Command Register
 ***************************************************************************/
/* GPIO_PER :: TestPortCommand :: TP_COMMAND [31:00] */
#define BCHP_GPIO_PER_TestPortCommand_TP_COMMAND_MASK              0xffffffff
#define BCHP_GPIO_PER_TestPortCommand_TP_COMMAND_SHIFT             0
#define BCHP_GPIO_PER_TestPortCommand_TP_COMMAND_DEFAULT           0x00000000

/***************************************************************************
 *diagReadBack - Diagnostic Readback Register
 ***************************************************************************/
/* GPIO_PER :: diagReadBack :: diagReadBack [31:00] */
#define BCHP_GPIO_PER_diagReadBack_diagReadBack_MASK               0xffffffff
#define BCHP_GPIO_PER_diagReadBack_diagReadBack_SHIFT              0

/***************************************************************************
 *diagReadBackHi - Diagnostic High Readback Register
 ***************************************************************************/
/* GPIO_PER :: diagReadBackHi :: reserved0 [31:08] */
#define BCHP_GPIO_PER_diagReadBackHi_reserved0_MASK                0xffffff00
#define BCHP_GPIO_PER_diagReadBackHi_reserved0_SHIFT               8

/* GPIO_PER :: diagReadBackHi :: diagReadBackHi [07:00] */
#define BCHP_GPIO_PER_diagReadBackHi_diagReadBackHi_MASK           0x000000ff
#define BCHP_GPIO_PER_diagReadBackHi_diagReadBackHi_SHIFT          0

/***************************************************************************
 *gpioReg - General Purpose Register
 ***************************************************************************/
/* GPIO_PER :: gpioReg :: gpio_register [31:00] */
#define BCHP_GPIO_PER_gpioReg_gpio_register_MASK                   0xffffffff
#define BCHP_GPIO_PER_gpioReg_gpio_register_SHIFT                  0

#endif /* #ifndef BCHP_GPIO_PER_H__ */

/* End of File */
