/****************************************************************************
 *
 * Broadcom Proprietary and Confidential.
 * (c) 2017 Broadcom. All rights reserved.
 * The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * Unless you and Broadcom execute a separate written software license
 * agreement governing use of this software, this software is licensed to
 * you under the terms of the GNU General Public License version 2 (the
 * "GPL"), available at [http://www.broadcom.com/licenses/GPLv2.php], with
 * the following added to such license:
 *
 * As a special exception, the copyright holders of this software give you
 * permission to link this software with independent modules, and to copy
 * and distribute the resulting executable under terms of your choice,
 * provided that you also meet, for each linked independent module, the
 * terms and conditions of the license of that module. An independent
 * module is a module which is not derived from this software. The special
 * exception does not apply to any modifications of the software.
 *
 * Notwithstanding the above, under no circumstances may you combine this
 * software in any way with any other Broadcom software provided under a
 * license other than the GPL, without Broadcom's express prior written
 * consent.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Tue Dec 13 03:38:32 2016
 *                 Full Compile MD5 Checksum  24fd6b55518d16e09b4d767927634264
 *                     (minus title and desc)
 *                 MD5 Checksum               0d6d5235c728b89a7482efc0b5587e6b
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_MBOX_CPUC_H__
#define BCHP_MBOX_CPUC_H__

/***************************************************************************
 *MBOX_CPUC
 ***************************************************************************/
#define BCHP_MBOX_CPUC_DATA0                     0x03800080 /* [RW][32] MBOX0 Register */
#define BCHP_MBOX_CPUC_DATA1                     0x03800084 /* [RW][32] MBOX1 Register */
#define BCHP_MBOX_CPUC_DATA2                     0x03800088 /* [RW][32] MBOX2 Register */
#define BCHP_MBOX_CPUC_DATA3                     0x0380008c /* [RW][32] MBOX3 Register */
#define BCHP_MBOX_CPUC_DATA4                     0x03800090 /* [RW][32] MBOX4 Register */
#define BCHP_MBOX_CPUC_DATA5                     0x03800094 /* [RW][32] MBOX5 Register */
#define BCHP_MBOX_CPUC_DATA6                     0x03800098 /* [RW][32] MBOX6 Register */
#define BCHP_MBOX_CPUC_DATA7                     0x0380009c /* [RW][32] MBOX7 Register */
#define BCHP_MBOX_CPUC_DATA8                     0x038000a0 /* [RW][32] MBOX8 Register */
#define BCHP_MBOX_CPUC_DATA9                     0x038000a4 /* [RW][32] MBOX9 Register */
#define BCHP_MBOX_CPUC_DATA10                    0x038000a8 /* [RW][32] MBOX10 Register */
#define BCHP_MBOX_CPUC_DATA11                    0x038000ac /* [RW][32] MBOX11 Register */
#define BCHP_MBOX_CPUC_DATA12                    0x038000b0 /* [RW][32] MBOX12 Register */
#define BCHP_MBOX_CPUC_DATA13                    0x038000b4 /* [RW][32] MBOX13 Register */
#define BCHP_MBOX_CPUC_DATA14                    0x038000b8 /* [RW][32] MBOX14 Register */
#define BCHP_MBOX_CPUC_DATA15                    0x038000bc /* [RW][32] MBOX15 Register */
#define BCHP_MBOX_CPUC_CFG0                      0x038000c0 /* [RW][32] MBOX0 Configuration Register */
#define BCHP_MBOX_CPUC_CFG1                      0x038000c4 /* [RW][32] MBOX1 Configuration Register */
#define BCHP_MBOX_CPUC_CFG2                      0x038000c8 /* [RW][32] MBOX2 Configuration Register */
#define BCHP_MBOX_CPUC_CFG3                      0x038000cc /* [RW][32] MBOX3 Configuration Register */
#define BCHP_MBOX_CPUC_CFG4                      0x038000d0 /* [RW][32] MBOX4 Configuration Register */
#define BCHP_MBOX_CPUC_CFG5                      0x038000d4 /* [RW][32] MBOX5 Configuration Register */
#define BCHP_MBOX_CPUC_CFG6                      0x038000d8 /* [RW][32] MBOX6 Configuration Register */
#define BCHP_MBOX_CPUC_CFG7                      0x038000dc /* [RW][32] MBOX7 Configuration Register */
#define BCHP_MBOX_CPUC_CFG8                      0x038000e0 /* [RW][32] MBOX8 Configuration Register */
#define BCHP_MBOX_CPUC_CFG9                      0x038000e4 /* [RW][32] MBOX9 Configuration Register */
#define BCHP_MBOX_CPUC_CFG10                     0x038000e8 /* [RW][32] MBOX10 Configuration Register */
#define BCHP_MBOX_CPUC_CFG11                     0x038000ec /* [RW][32] MBOX11 Configuration Register */
#define BCHP_MBOX_CPUC_CFG12                     0x038000f0 /* [RW][32] MBOX12 Configuration Register */
#define BCHP_MBOX_CPUC_CFG13                     0x038000f4 /* [RW][32] MBOX13 Configuration Register */
#define BCHP_MBOX_CPUC_CFG14                     0x038000f8 /* [RW][32] MBOX14 Configuration Register */
#define BCHP_MBOX_CPUC_CFG15                     0x038000fc /* [RW][32] MBOX15 Configuration Register */

/***************************************************************************
 *DATA0 - MBOX0 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA0 :: reserved0 [31:07] */
#define BCHP_MBOX_CPUC_DATA0_reserved0_MASK                        0xffffff80
#define BCHP_MBOX_CPUC_DATA0_reserved0_SHIFT                       7

/* MBOX_CPUC :: DATA0 :: U2G_SELECT [06:06] */
#define BCHP_MBOX_CPUC_DATA0_U2G_SELECT_MASK                       0x00000040
#define BCHP_MBOX_CPUC_DATA0_U2G_SELECT_SHIFT                      6

/* MBOX_CPUC :: DATA0 :: CHIP_IN_BBM [05:05] */
#define BCHP_MBOX_CPUC_DATA0_CHIP_IN_BBM_MASK                      0x00000020
#define BCHP_MBOX_CPUC_DATA0_CHIP_IN_BBM_SHIFT                     5

/* MBOX_CPUC :: DATA0 :: reserved1 [04:04] */
#define BCHP_MBOX_CPUC_DATA0_reserved1_MASK                        0x00000010
#define BCHP_MBOX_CPUC_DATA0_reserved1_SHIFT                       4

/* MBOX_CPUC :: DATA0 :: POWER_STATE [03:02] */
#define BCHP_MBOX_CPUC_DATA0_POWER_STATE_MASK                      0x0000000c
#define BCHP_MBOX_CPUC_DATA0_POWER_STATE_SHIFT                     2

/* MBOX_CPUC :: DATA0 :: reserved2 [01:01] */
#define BCHP_MBOX_CPUC_DATA0_reserved2_MASK                        0x00000002
#define BCHP_MBOX_CPUC_DATA0_reserved2_SHIFT                       1

/* MBOX_CPUC :: DATA0 :: DISCHARGE_ENA [00:00] */
#define BCHP_MBOX_CPUC_DATA0_DISCHARGE_ENA_MASK                    0x00000001
#define BCHP_MBOX_CPUC_DATA0_DISCHARGE_ENA_SHIFT                   0

/***************************************************************************
 *DATA1 - MBOX1 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA1 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA1_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA1_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA1_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA2 - MBOX2 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA2 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA2_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA2_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA2_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA3 - MBOX3 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA3 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA3_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA3_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA3_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA4 - MBOX4 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA4 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA4_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA4_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA4_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA5 - MBOX5 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA5 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA5_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA5_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA5_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA6 - MBOX6 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA6 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA6_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA6_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA6_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA7 - MBOX7 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA7 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA7_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA7_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA7_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA8 - MBOX8 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA8 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA8_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA8_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA8_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA9 - MBOX9 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA9 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA9_MBOX_IN_MASK                          0xffffffff
#define BCHP_MBOX_CPUC_DATA9_MBOX_IN_SHIFT                         0
#define BCHP_MBOX_CPUC_DATA9_MBOX_IN_DEFAULT                       0x00000000

/***************************************************************************
 *DATA10 - MBOX10 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA10 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA10_MBOX_IN_MASK                         0xffffffff
#define BCHP_MBOX_CPUC_DATA10_MBOX_IN_SHIFT                        0
#define BCHP_MBOX_CPUC_DATA10_MBOX_IN_DEFAULT                      0x00000000

/***************************************************************************
 *DATA11 - MBOX11 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA11 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA11_MBOX_IN_MASK                         0xffffffff
#define BCHP_MBOX_CPUC_DATA11_MBOX_IN_SHIFT                        0
#define BCHP_MBOX_CPUC_DATA11_MBOX_IN_DEFAULT                      0x00000000

/***************************************************************************
 *DATA12 - MBOX12 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA12 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA12_MBOX_IN_MASK                         0xffffffff
#define BCHP_MBOX_CPUC_DATA12_MBOX_IN_SHIFT                        0
#define BCHP_MBOX_CPUC_DATA12_MBOX_IN_DEFAULT                      0x00000000

/***************************************************************************
 *DATA13 - MBOX13 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA13 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA13_MBOX_IN_MASK                         0xffffffff
#define BCHP_MBOX_CPUC_DATA13_MBOX_IN_SHIFT                        0
#define BCHP_MBOX_CPUC_DATA13_MBOX_IN_DEFAULT                      0x00000000

/***************************************************************************
 *DATA14 - MBOX14 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA14 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA14_MBOX_IN_MASK                         0xffffffff
#define BCHP_MBOX_CPUC_DATA14_MBOX_IN_SHIFT                        0
#define BCHP_MBOX_CPUC_DATA14_MBOX_IN_DEFAULT                      0x00000000

/***************************************************************************
 *DATA15 - MBOX15 Register
 ***************************************************************************/
/* MBOX_CPUC :: DATA15 :: MBOX_IN [31:00] */
#define BCHP_MBOX_CPUC_DATA15_MBOX_IN_MASK                         0xffffffff
#define BCHP_MBOX_CPUC_DATA15_MBOX_IN_SHIFT                        0
#define BCHP_MBOX_CPUC_DATA15_MBOX_IN_DEFAULT                      0x00000000

/***************************************************************************
 *CFG0 - MBOX0 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG0 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG0_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG0_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG0 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG0_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG0_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG0_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG0 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG0_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG0_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG0_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG0 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG0_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG0_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG0 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG0_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG0_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG0_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG1 - MBOX1 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG1 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG1_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG1_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG1 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG1_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG1_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG1_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG1 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG1_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG1_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG1_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG1 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG1_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG1_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG1 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG1_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG1_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG1_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG2 - MBOX2 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG2 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG2_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG2_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG2 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG2_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG2_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG2_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG2 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG2_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG2_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG2_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG2 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG2_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG2_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG2 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG2_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG2_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG2_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG3 - MBOX3 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG3 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG3_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG3_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG3 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG3_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG3_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG3_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG3 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG3_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG3_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG3_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG3 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG3_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG3_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG3 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG3_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG3_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG3_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG4 - MBOX4 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG4 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG4_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG4_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG4 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG4_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG4_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG4_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG4 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG4_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG4_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG4_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG4 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG4_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG4_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG4 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG4_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG4_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG4_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG5 - MBOX5 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG5 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG5_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG5_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG5 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG5_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG5_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG5_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG5 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG5_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG5_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG5_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG5 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG5_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG5_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG5 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG5_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG5_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG5_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG6 - MBOX6 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG6 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG6_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG6_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG6 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG6_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG6_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG6_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG6 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG6_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG6_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG6_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG6 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG6_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG6_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG6 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG6_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG6_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG6_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG7 - MBOX7 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG7 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG7_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG7_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG7 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG7_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG7_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG7_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG7 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG7_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG7_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG7_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG7 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG7_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG7_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG7 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG7_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG7_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG7_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG8 - MBOX8 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG8 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG8_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG8_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG8 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG8_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG8_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG8_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG8 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG8_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG8_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG8_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG8 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG8_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG8_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG8 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG8_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG8_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG8_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG9 - MBOX9 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG9 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG9_reserved0_MASK                         0xfffffc00
#define BCHP_MBOX_CPUC_CFG9_reserved0_SHIFT                        10

/* MBOX_CPUC :: CFG9 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG9_MBOX_LOCK_MASK                         0x00000200
#define BCHP_MBOX_CPUC_CFG9_MBOX_LOCK_SHIFT                        9
#define BCHP_MBOX_CPUC_CFG9_MBOX_LOCK_DEFAULT                      0x00000000

/* MBOX_CPUC :: CFG9 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG9_MBOX_CLR_ON_READ_MASK                  0x00000100
#define BCHP_MBOX_CPUC_CFG9_MBOX_CLR_ON_READ_SHIFT                 8
#define BCHP_MBOX_CPUC_CFG9_MBOX_CLR_ON_READ_DEFAULT               0x00000000

/* MBOX_CPUC :: CFG9 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG9_reserved1_MASK                         0x00000080
#define BCHP_MBOX_CPUC_CFG9_reserved1_SHIFT                        7

/* MBOX_CPUC :: CFG9 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG9_MBOX_LOCK_SRC_MASK                     0x0000007f
#define BCHP_MBOX_CPUC_CFG9_MBOX_LOCK_SRC_SHIFT                    0
#define BCHP_MBOX_CPUC_CFG9_MBOX_LOCK_SRC_DEFAULT                  0x00000000

/***************************************************************************
 *CFG10 - MBOX10 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG10 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG10_reserved0_MASK                        0xfffffc00
#define BCHP_MBOX_CPUC_CFG10_reserved0_SHIFT                       10

/* MBOX_CPUC :: CFG10 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG10_MBOX_LOCK_MASK                        0x00000200
#define BCHP_MBOX_CPUC_CFG10_MBOX_LOCK_SHIFT                       9
#define BCHP_MBOX_CPUC_CFG10_MBOX_LOCK_DEFAULT                     0x00000000

/* MBOX_CPUC :: CFG10 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG10_MBOX_CLR_ON_READ_MASK                 0x00000100
#define BCHP_MBOX_CPUC_CFG10_MBOX_CLR_ON_READ_SHIFT                8
#define BCHP_MBOX_CPUC_CFG10_MBOX_CLR_ON_READ_DEFAULT              0x00000000

/* MBOX_CPUC :: CFG10 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG10_reserved1_MASK                        0x00000080
#define BCHP_MBOX_CPUC_CFG10_reserved1_SHIFT                       7

/* MBOX_CPUC :: CFG10 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG10_MBOX_LOCK_SRC_MASK                    0x0000007f
#define BCHP_MBOX_CPUC_CFG10_MBOX_LOCK_SRC_SHIFT                   0
#define BCHP_MBOX_CPUC_CFG10_MBOX_LOCK_SRC_DEFAULT                 0x00000000

/***************************************************************************
 *CFG11 - MBOX11 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG11 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG11_reserved0_MASK                        0xfffffc00
#define BCHP_MBOX_CPUC_CFG11_reserved0_SHIFT                       10

/* MBOX_CPUC :: CFG11 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG11_MBOX_LOCK_MASK                        0x00000200
#define BCHP_MBOX_CPUC_CFG11_MBOX_LOCK_SHIFT                       9
#define BCHP_MBOX_CPUC_CFG11_MBOX_LOCK_DEFAULT                     0x00000000

/* MBOX_CPUC :: CFG11 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG11_MBOX_CLR_ON_READ_MASK                 0x00000100
#define BCHP_MBOX_CPUC_CFG11_MBOX_CLR_ON_READ_SHIFT                8
#define BCHP_MBOX_CPUC_CFG11_MBOX_CLR_ON_READ_DEFAULT              0x00000000

/* MBOX_CPUC :: CFG11 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG11_reserved1_MASK                        0x00000080
#define BCHP_MBOX_CPUC_CFG11_reserved1_SHIFT                       7

/* MBOX_CPUC :: CFG11 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG11_MBOX_LOCK_SRC_MASK                    0x0000007f
#define BCHP_MBOX_CPUC_CFG11_MBOX_LOCK_SRC_SHIFT                   0
#define BCHP_MBOX_CPUC_CFG11_MBOX_LOCK_SRC_DEFAULT                 0x00000000

/***************************************************************************
 *CFG12 - MBOX12 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG12 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG12_reserved0_MASK                        0xfffffc00
#define BCHP_MBOX_CPUC_CFG12_reserved0_SHIFT                       10

/* MBOX_CPUC :: CFG12 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG12_MBOX_LOCK_MASK                        0x00000200
#define BCHP_MBOX_CPUC_CFG12_MBOX_LOCK_SHIFT                       9
#define BCHP_MBOX_CPUC_CFG12_MBOX_LOCK_DEFAULT                     0x00000000

/* MBOX_CPUC :: CFG12 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG12_MBOX_CLR_ON_READ_MASK                 0x00000100
#define BCHP_MBOX_CPUC_CFG12_MBOX_CLR_ON_READ_SHIFT                8
#define BCHP_MBOX_CPUC_CFG12_MBOX_CLR_ON_READ_DEFAULT              0x00000000

/* MBOX_CPUC :: CFG12 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG12_reserved1_MASK                        0x00000080
#define BCHP_MBOX_CPUC_CFG12_reserved1_SHIFT                       7

/* MBOX_CPUC :: CFG12 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG12_MBOX_LOCK_SRC_MASK                    0x0000007f
#define BCHP_MBOX_CPUC_CFG12_MBOX_LOCK_SRC_SHIFT                   0
#define BCHP_MBOX_CPUC_CFG12_MBOX_LOCK_SRC_DEFAULT                 0x00000000

/***************************************************************************
 *CFG13 - MBOX13 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG13 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG13_reserved0_MASK                        0xfffffc00
#define BCHP_MBOX_CPUC_CFG13_reserved0_SHIFT                       10

/* MBOX_CPUC :: CFG13 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG13_MBOX_LOCK_MASK                        0x00000200
#define BCHP_MBOX_CPUC_CFG13_MBOX_LOCK_SHIFT                       9
#define BCHP_MBOX_CPUC_CFG13_MBOX_LOCK_DEFAULT                     0x00000000

/* MBOX_CPUC :: CFG13 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG13_MBOX_CLR_ON_READ_MASK                 0x00000100
#define BCHP_MBOX_CPUC_CFG13_MBOX_CLR_ON_READ_SHIFT                8
#define BCHP_MBOX_CPUC_CFG13_MBOX_CLR_ON_READ_DEFAULT              0x00000000

/* MBOX_CPUC :: CFG13 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG13_reserved1_MASK                        0x00000080
#define BCHP_MBOX_CPUC_CFG13_reserved1_SHIFT                       7

/* MBOX_CPUC :: CFG13 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG13_MBOX_LOCK_SRC_MASK                    0x0000007f
#define BCHP_MBOX_CPUC_CFG13_MBOX_LOCK_SRC_SHIFT                   0
#define BCHP_MBOX_CPUC_CFG13_MBOX_LOCK_SRC_DEFAULT                 0x00000000

/***************************************************************************
 *CFG14 - MBOX14 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG14 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG14_reserved0_MASK                        0xfffffc00
#define BCHP_MBOX_CPUC_CFG14_reserved0_SHIFT                       10

/* MBOX_CPUC :: CFG14 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG14_MBOX_LOCK_MASK                        0x00000200
#define BCHP_MBOX_CPUC_CFG14_MBOX_LOCK_SHIFT                       9
#define BCHP_MBOX_CPUC_CFG14_MBOX_LOCK_DEFAULT                     0x00000000

/* MBOX_CPUC :: CFG14 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG14_MBOX_CLR_ON_READ_MASK                 0x00000100
#define BCHP_MBOX_CPUC_CFG14_MBOX_CLR_ON_READ_SHIFT                8
#define BCHP_MBOX_CPUC_CFG14_MBOX_CLR_ON_READ_DEFAULT              0x00000000

/* MBOX_CPUC :: CFG14 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG14_reserved1_MASK                        0x00000080
#define BCHP_MBOX_CPUC_CFG14_reserved1_SHIFT                       7

/* MBOX_CPUC :: CFG14 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG14_MBOX_LOCK_SRC_MASK                    0x0000007f
#define BCHP_MBOX_CPUC_CFG14_MBOX_LOCK_SRC_SHIFT                   0
#define BCHP_MBOX_CPUC_CFG14_MBOX_LOCK_SRC_DEFAULT                 0x00000000

/***************************************************************************
 *CFG15 - MBOX15 Configuration Register
 ***************************************************************************/
/* MBOX_CPUC :: CFG15 :: reserved0 [31:10] */
#define BCHP_MBOX_CPUC_CFG15_reserved0_MASK                        0xfffffc00
#define BCHP_MBOX_CPUC_CFG15_reserved0_SHIFT                       10

/* MBOX_CPUC :: CFG15 :: MBOX_LOCK [09:09] */
#define BCHP_MBOX_CPUC_CFG15_MBOX_LOCK_MASK                        0x00000200
#define BCHP_MBOX_CPUC_CFG15_MBOX_LOCK_SHIFT                       9
#define BCHP_MBOX_CPUC_CFG15_MBOX_LOCK_DEFAULT                     0x00000000

/* MBOX_CPUC :: CFG15 :: MBOX_CLR_ON_READ [08:08] */
#define BCHP_MBOX_CPUC_CFG15_MBOX_CLR_ON_READ_MASK                 0x00000100
#define BCHP_MBOX_CPUC_CFG15_MBOX_CLR_ON_READ_SHIFT                8
#define BCHP_MBOX_CPUC_CFG15_MBOX_CLR_ON_READ_DEFAULT              0x00000000

/* MBOX_CPUC :: CFG15 :: reserved1 [07:07] */
#define BCHP_MBOX_CPUC_CFG15_reserved1_MASK                        0x00000080
#define BCHP_MBOX_CPUC_CFG15_reserved1_SHIFT                       7

/* MBOX_CPUC :: CFG15 :: MBOX_LOCK_SRC [06:00] */
#define BCHP_MBOX_CPUC_CFG15_MBOX_LOCK_SRC_MASK                    0x0000007f
#define BCHP_MBOX_CPUC_CFG15_MBOX_LOCK_SRC_SHIFT                   0
#define BCHP_MBOX_CPUC_CFG15_MBOX_LOCK_SRC_DEFAULT                 0x00000000

#endif /* #ifndef BCHP_MBOX_CPUC_H__ */

/* End of File */
