/****************************************************************************
 *
 * Broadcom Proprietary and Confidential.
 * (c) 2017 Broadcom. All rights reserved.
 * The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * Unless you and Broadcom execute a separate written software license
 * agreement governing use of this software, this software is licensed to
 * you under the terms of the GNU General Public License version 2 (the
 * "GPL"), available at [http://www.broadcom.com/licenses/GPLv2.php], with
 * the following added to such license:
 *
 * As a special exception, the copyright holders of this software give you
 * permission to link this software with independent modules, and to copy
 * and distribute the resulting executable under terms of your choice,
 * provided that you also meet, for each linked independent module, the
 * terms and conditions of the license of that module. An independent
 * module is a module which is not derived from this software. The special
 * exception does not apply to any modifications of the software.
 *
 * Notwithstanding the above, under no circumstances may you combine this
 * software in any way with any other Broadcom software provided under a
 * license other than the GPL, without Broadcom's express prior written
 * consent.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Jun 10 03:09:38 2015
 *                 Full Compile MD5 Checksum  e8bde4108283f67d401938287dbb6bde
 *                     (minus title and desc)
 *                 MD5 Checksum               56f0f944fbd407545cd964e7b4e7f7b0
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_UNIMAC_INTERFACE0_UNI3_H__
#define BCHP_UNIMAC_INTERFACE0_UNI3_H__

/***************************************************************************
 *UNIMAC_INTERFACE0_UNI3 - UNIMAC Interface registers
 ***************************************************************************/
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL      0x00400600 /* [RW] Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CLR_MIB      0x00400604 /* [RW] Clear MIB Counter */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RXERR_MASK   0x00400608 /* [RW] MAC RxErr Mask */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STAT_UPDATE_MASK 0x0040060c /* [RW] MAC Stat Update Mask */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MIB_PKTMAX   0x00400610 /* [RW] MIB Packet Max Size */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH   0x00400614 /* [RW] Flush Transmit and Receive FIFO */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT   0x00400618 /* [RW] RSV Select For RxDmaFrameStat */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT 0x0040061c /* [RW] Enable Drop Packet */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ   0x00400620 /* [RW] Enable Interrupt */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL  0x00400624 /* [RW] Priority Pause Packet Control */
#define BCHP_UNIMAC_INTERFACE0_UNI3_BACK_PRESSURE 0x00400628 /* [RW] Enable Back Pressure */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD     0x0040062c /* [RW] MDIO Command Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG     0x00400630 /* [RW] MDIO Configuration Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL   0x00400634 /* [RW] RGMII Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_LED_CTRL 0x00400638 /* [RW] RGMII LED Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RX_TIME_STAMP 0x0040063c /* [RW] Receive Time Stamp Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS   0x00400640 /* [RO] MAC Status Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS   0x00400644 /* [RW] Interrupt Status Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_STATUS   0x00400648 /* [RO] Priority Pause Packet Status Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_OVERFLOW_COUNTER 0x0040064c /* [RO] Receive Overflow Counter */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL 0x00400650 /* [RW] RGMII ATE RX Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS 0x00400654 /* [RO] RGMII ATE RX Status Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0 0x00400658 /* [RW] RGMII ATE TX Control 0 Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1 0x0040065c /* [RW] RGMII ATE TX Control 1 Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL 0x00400660 /* [RW] RGMII TX Clock Delay Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS 0x00400664 /* [RO] RGMII In-band Status Delay Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_INTF_DIAG_OUT 0x00400668 /* [RO] Interface diagnostic read value */
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS 0x0040066c /* [RO] Unimac Core Status */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL 0x00400680 /* [RW] Time Stamp Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_MODE 0x00400684 /* [RW] Time Stamp Sync Mode Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_INCREMENT 0x00400688 /* [RW] Time Stamp Increment Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_STEP 0x0040068c /* [RW] Time Stamp Phase Step Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_DURATION 0x00400690 /* [RW] Time Stamp Phase Duration Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_STEP 0x00400694 /* [RW] Time Stamp Frequency Step Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_PERIOD 0x00400698 /* [RW] Time Stamp Frequency Period Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_ROLL_OVER 0x0040069c /* [RW] Time Stamp Roll Over Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_TIMER_LOCAL 0x004006a0 /* [RW] Time Stamp Free Running Timer Local Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_SECOND 0x004006a4 /* [RW] Time Stamp Free Running Second Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_EPOCH 0x004006a8 /* [RW] Time Stamp Free Running Epoch Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_LOCAL 0x004006ac /* [RW] Time Stamp Synchronous Timer Local Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SECOND 0x004006b0 /* [RW] Time Stamp Synchronous Second Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_EPOCH 0x004006b4 /* [RW] Time Stamp Synchronous Epoch Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_EPOCH_CNT 0x004006b8 /* [RW] Time Stamp Epoch Count Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_TIMER_LOCAL 0x004006bc /* [RW] Time Stamp Snap Shot Free Running Timer Local Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_SECOND 0x004006c0 /* [RW] Time Stamp Snap Shot Free Running Second Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH 0x004006c4 /* [RW] Time Stamp Snap Shot Free Running Epoch Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_TIMER_LOCAL 0x004006c8 /* [RW] Time Stamp Snap Shot Synchronous Timer Local Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_SECOND 0x004006cc /* [RW] Time Stamp Snap Shot Synchronous Second Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_EPOCH 0x004006d0 /* [RW] Time Stamp Snap Shot Synchronous Epoch Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_SLOT 0x004006d4 /* [RW] Time Stamp Synchronous Timer Slot Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SLOT_BASE 0x004006d8 /* [RW] Time Stamp Synchronous Slot And Base Timer Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_PCR 0x004006dc /* [RW] Time Stamp Synchronous PCR Timer Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_WAIT_THRESHOLD 0x004006e0 /* [RW] Time Stamp Synchronous Wait Threshold Timer Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE 0x004006e4 /* [RW] Time Stamp Disable Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL     0x004006f0 /* [RW] Magic Packet Control Registers */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_MS       0x004006f4 /* [RW] Magic Packet Optional password byte 0 and 1 */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_LS       0x004006f8 /* [RW] Magic Packet Optional password byte 2 ~ 5 */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL        0x004006fc /* [RW] HFB Control Register */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0   0x00400700 /* [RW] HFB Filter Length Register 0 */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1   0x00400704 /* [RW] HFB Filter Length Register 1 */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2   0x00400708 /* [RW] HFB Filter Length Register 2 */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3   0x0040070c /* [RW] HFB Filter Length Register 3 */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS   0x00400710 /* [RO] Wake-on-LAN status */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PWR_CTRL     0x00400714 /* [RW] Power Control - controls for switching to low frequency device clock */

/***************************************************************************
 *CONTROL - Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: RX_Byte_padding [31:20] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_RX_Byte_padding_MASK   0xfff00000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_RX_Byte_padding_SHIFT  20
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_RX_Byte_padding_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: reserved0 [19:17] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_reserved0_MASK         0x000e0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_reserved0_SHIFT        17

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: LPI_Enable [16:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_LPI_Enable_MASK        0x00010000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_LPI_Enable_SHIFT       16
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_LPI_Enable_DEFAULT     0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: Enable_EAV [15:15] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Enable_EAV_MASK        0x00008000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Enable_EAV_SHIFT       15
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Enable_EAV_DEFAULT     0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: GMII_pad_test_en [14:14] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_GMII_pad_test_en_MASK  0x00004000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_GMII_pad_test_en_SHIFT 14
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_GMII_pad_test_en_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: MOCA_clock_enable [13:13] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_MOCA_clock_enable_MASK 0x00002000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_MOCA_clock_enable_SHIFT 13
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_MOCA_clock_enable_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: RX_2Byte_align [12:12] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_RX_2Byte_align_MASK    0x00001000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_RX_2Byte_align_SHIFT   12
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_RX_2Byte_align_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: Transfer_on_eop [11:11] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Transfer_on_eop_MASK   0x00000800
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Transfer_on_eop_SHIFT  11
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Transfer_on_eop_DEFAULT 0x00000001

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: Select_onchip_phy [10:10] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Select_onchip_phy_MASK 0x00000400
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Select_onchip_phy_SHIFT 10
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Select_onchip_phy_DEFAULT 0x00000001

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: Backpressure_mux [09:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Backpressure_mux_MASK  0x00000200
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Backpressure_mux_SHIFT 9
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Backpressure_mux_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: FPM_Backpressure [08:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_FPM_Backpressure_MASK  0x00000100
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_FPM_Backpressure_SHIFT 8
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_FPM_Backpressure_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: Token_Backpressure [07:07] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Token_Backpressure_MASK 0x00000080
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Token_Backpressure_SHIFT 7
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Token_Backpressure_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: Tx_Channel_Priority [06:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Tx_Channel_Priority_MASK 0x00000060
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Tx_Channel_Priority_SHIFT 5
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Tx_Channel_Priority_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: TimeStamp_Ref_Select [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_TimeStamp_Ref_Select_MASK 0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_TimeStamp_Ref_Select_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_TimeStamp_Ref_Select_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: PCR_Timer_Select [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_PCR_Timer_Select_MASK  0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_PCR_Timer_Select_SHIFT 3
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_PCR_Timer_Select_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: PCR_Timer_1usec_11usec [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_PCR_Timer_1usec_11usec_MASK 0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_PCR_Timer_1usec_11usec_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_PCR_Timer_1usec_11usec_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: Clk125_Select [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Clk125_Select_MASK     0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Clk125_Select_SHIFT    1
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_Clk125_Select_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CONTROL :: DirectGMII [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_DirectGMII_MASK        0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_DirectGMII_SHIFT       0
#define BCHP_UNIMAC_INTERFACE0_UNI3_CONTROL_DirectGMII_DEFAULT     0x00000001

/***************************************************************************
 *CLR_MIB - Clear MIB Counter
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: CLR_MIB :: reserved0 [31:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CLR_MIB_reserved0_MASK         0xfffffffe
#define BCHP_UNIMAC_INTERFACE0_UNI3_CLR_MIB_reserved0_SHIFT        1

/* UNIMAC_INTERFACE0_UNI3 :: CLR_MIB :: Clear_MIB_counter [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CLR_MIB_Clear_MIB_counter_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_CLR_MIB_Clear_MIB_counter_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_CLR_MIB_Clear_MIB_counter_DEFAULT 0x00000000

/***************************************************************************
 *RXERR_MASK - MAC RxErr Mask
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RXERR_MASK :: reserved0 [31:18] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RXERR_MASK_reserved0_MASK      0xfffc0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RXERR_MASK_reserved0_SHIFT     18

/* UNIMAC_INTERFACE0_UNI3 :: RXERR_MASK :: MAC_RxErr_Mask [17:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RXERR_MASK_MAC_RxErr_Mask_MASK 0x0003ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_RXERR_MASK_MAC_RxErr_Mask_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RXERR_MASK_MAC_RxErr_Mask_DEFAULT 0x00000000

/***************************************************************************
 *MAC_STAT_UPDATE_MASK - MAC Stat Update Mask
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: MAC_STAT_UPDATE_MASK :: reserved0 [31:18] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STAT_UPDATE_MASK_reserved0_MASK 0xfffc0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STAT_UPDATE_MASK_reserved0_SHIFT 18

/* UNIMAC_INTERFACE0_UNI3 :: MAC_STAT_UPDATE_MASK :: MAC_Stat_Update [17:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STAT_UPDATE_MASK_MAC_Stat_Update_MASK 0x0003ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STAT_UPDATE_MASK_MAC_Stat_Update_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STAT_UPDATE_MASK_MAC_Stat_Update_DEFAULT 0x00000000

/***************************************************************************
 *MIB_PKTMAX - MIB Packet Max Size
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: MIB_PKTMAX :: reserved0 [31:14] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MIB_PKTMAX_reserved0_MASK      0xffffc000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MIB_PKTMAX_reserved0_SHIFT     14

/* UNIMAC_INTERFACE0_UNI3 :: MIB_PKTMAX :: MIB_Pkt_Max [13:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MIB_PKTMAX_MIB_Pkt_Max_MASK    0x00003fff
#define BCHP_UNIMAC_INTERFACE0_UNI3_MIB_PKTMAX_MIB_Pkt_Max_SHIFT   0
#define BCHP_UNIMAC_INTERFACE0_UNI3_MIB_PKTMAX_MIB_Pkt_Max_DEFAULT 0x000005ee

/***************************************************************************
 *FIFO_FLUSH - Flush Transmit and Receive FIFO
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: FIFO_FLUSH :: reserved0 [31:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_reserved0_MASK      0xfffffff8
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_reserved0_SHIFT     3

/* UNIMAC_INTERFACE0_UNI3 :: FIFO_FLUSH :: Transmit_High_Priority_FIFO_Flush [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Transmit_High_Priority_FIFO_Flush_MASK 0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Transmit_High_Priority_FIFO_Flush_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Transmit_High_Priority_FIFO_Flush_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FIFO_FLUSH :: Transmit_Low_Priority_FIFO_Flush [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Transmit_Low_Priority_FIFO_Flush_MASK 0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Transmit_Low_Priority_FIFO_Flush_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Transmit_Low_Priority_FIFO_Flush_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FIFO_FLUSH :: Receive_FIFO_Flush [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Receive_FIFO_Flush_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Receive_FIFO_Flush_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_FIFO_FLUSH_Receive_FIFO_Flush_DEFAULT 0x00000000

/***************************************************************************
 *RSV_SELECT - RSV Select For RxDmaFrameStat
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RSV_SELECT :: reserved0 [31:12] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_reserved0_MASK      0xfffff000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_reserved0_SHIFT     12

/* UNIMAC_INTERFACE0_UNI3 :: RSV_SELECT :: RSV_33_Select [11:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_33_Select_MASK  0x00000f00
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_33_Select_SHIFT 8
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_33_Select_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RSV_SELECT :: RSV_32_Select [07:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_32_Select_MASK  0x000000f0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_32_Select_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_32_Select_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RSV_SELECT :: RSV_31_Select [03:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_31_Select_MASK  0x0000000f
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_31_Select_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RSV_SELECT_RSV_31_Select_DEFAULT 0x00000000

/***************************************************************************
 *ENABLE_DROP_PKT - Enable Drop Packet
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: reserved0 [31:10] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_reserved0_MASK 0xfffffc00
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_reserved0_SHIFT 10

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_Receive_Full [09:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Receive_Full_MASK 0x00000200
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Receive_Full_SHIFT 9
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Receive_Full_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_RUNT_Truncasted [08:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_RUNT_Truncasted_MASK 0x00000100
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_RUNT_Truncasted_SHIFT 8
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_RUNT_Truncasted_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_Frame_Truncasted [07:07] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Frame_Truncasted_MASK 0x00000080
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Frame_Truncasted_SHIFT 7
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Frame_Truncasted_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_Unicast [06:06] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Unicast_MASK 0x00000040
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Unicast_SHIFT 6
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Unicast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_VLAN [05:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_VLAN_MASK 0x00000020
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_VLAN_SHIFT 5
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_VLAN_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_Control [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Control_MASK 0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Control_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Control_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_BroadCast [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_BroadCast_MASK 0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_BroadCast_SHIFT 3
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_BroadCast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_Multicast [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Multicast_MASK 0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Multicast_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Multicast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_CRC_Error [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_CRC_Error_MASK 0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_CRC_Error_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_CRC_Error_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_DROP_PKT :: Drop_Receive_Error [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Receive_Error_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Receive_Error_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_DROP_PKT_Drop_Receive_Error_DEFAULT 0x00000000

/***************************************************************************
 *ENABLE_IRQ - Enable Interrupt
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: reserved0 [31:13] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_reserved0_MASK      0xffffe000
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_reserved0_SHIFT     13

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_LinkUp [12:12] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_LinkUp_MASK     0x00001000
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_LinkUp_SHIFT    12

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_LinkDown [11:11] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_LinkDown_MASK   0x00000800
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_LinkDown_SHIFT  11
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_LinkDown_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_PPP_Validated [10:10] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_PPP_Validated_MASK 0x00000400
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_PPP_Validated_SHIFT 10
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_PPP_Validated_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_Receive_Full [09:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Receive_Full_MASK 0x00000200
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Receive_Full_SHIFT 9
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Receive_Full_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_RUNT_Truncasted [08:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_RUNT_Truncasted_MASK 0x00000100
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_RUNT_Truncasted_SHIFT 8
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_RUNT_Truncasted_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_Frame_Truncasted [07:07] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Frame_Truncasted_MASK 0x00000080
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Frame_Truncasted_SHIFT 7
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Frame_Truncasted_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_Unicast [06:06] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Unicast_MASK    0x00000040
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Unicast_SHIFT   6
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Unicast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_VLAN [05:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_VLAN_MASK       0x00000020
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_VLAN_SHIFT      5
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_VLAN_DEFAULT    0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_Control [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Control_MASK    0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Control_SHIFT   4
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Control_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_BroadCast [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_BroadCast_MASK  0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_BroadCast_SHIFT 3
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_BroadCast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_Multicast [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Multicast_MASK  0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Multicast_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Multicast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_CRC_Error [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_CRC_Error_MASK  0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_CRC_Error_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_CRC_Error_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: ENABLE_IRQ :: Irq_Receive_Error [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Receive_Error_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Receive_Error_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_ENABLE_IRQ_Irq_Receive_Error_DEFAULT 0x00000000

/***************************************************************************
 *PPP_CONTROL - Priority Pause Packet Control
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: PPP_CONTROL :: reserved0 [31:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_reserved0_MASK     0xfffffe00
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_reserved0_SHIFT    9

/* UNIMAC_INTERFACE0_UNI3 :: PPP_CONTROL :: PPP_GEN [08:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_PPP_GEN_MASK       0x00000100
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_PPP_GEN_SHIFT      8
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_PPP_GEN_DEFAULT    0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: PPP_CONTROL :: PPP_CLS_Enable [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_PPP_CLS_Enable_MASK 0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_PPP_CLS_Enable_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_CONTROL_PPP_CLS_Enable_DEFAULT 0x00000000

/***************************************************************************
 *BACK_PRESSURE - Enable Back Pressure
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: BACK_PRESSURE :: reserved0 [31:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_BACK_PRESSURE_reserved0_MASK   0xfffffffe
#define BCHP_UNIMAC_INTERFACE0_UNI3_BACK_PRESSURE_reserved0_SHIFT  1

/* UNIMAC_INTERFACE0_UNI3 :: BACK_PRESSURE :: Back_Pressure_Enable [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_BACK_PRESSURE_Back_Pressure_Enable_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_BACK_PRESSURE_Back_Pressure_Enable_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_BACK_PRESSURE_Back_Pressure_Enable_DEFAULT 0x00000000

/***************************************************************************
 *MDIO_CMD - MDIO Command Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CMD :: reserved0 [31:30] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_reserved0_MASK        0xc0000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_reserved0_SHIFT       30

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CMD :: mdio_busy [29:29] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_mdio_busy_MASK        0x20000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_mdio_busy_SHIFT       29
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_mdio_busy_DEFAULT     0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CMD :: fail [28:28] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_fail_MASK             0x10000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_fail_SHIFT            28
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_fail_DEFAULT          0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CMD :: op_code [27:26] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_op_code_MASK          0x0c000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_op_code_SHIFT         26
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_op_code_DEFAULT       0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CMD :: phy_prt_addr [25:21] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_phy_prt_addr_MASK     0x03e00000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_phy_prt_addr_SHIFT    21
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_phy_prt_addr_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CMD :: reg_dec_addr [20:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_reg_dec_addr_MASK     0x001f0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_reg_dec_addr_SHIFT    16
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_reg_dec_addr_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CMD :: data_addr [15:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_data_addr_MASK        0x0000ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_data_addr_SHIFT       0
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CMD_data_addr_DEFAULT     0x00000000

/***************************************************************************
 *MDIO_CFG - MDIO Configuration Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CFG :: reserved0 [31:13] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_reserved0_MASK        0xffffe000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_reserved0_SHIFT       13

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CFG :: supress_preamble [12:12] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_supress_preamble_MASK 0x00001000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_supress_preamble_SHIFT 12
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_supress_preamble_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CFG :: reserved1 [11:10] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_reserved1_MASK        0x00000c00
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_reserved1_SHIFT       10

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CFG :: mdio_clk_divider [09:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_mdio_clk_divider_MASK 0x000003f0
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_mdio_clk_divider_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_mdio_clk_divider_DEFAULT 0x0000000c

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CFG :: reserved2 [03:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_reserved2_MASK        0x0000000e
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_reserved2_SHIFT       1

/* UNIMAC_INTERFACE0_UNI3 :: MDIO_CFG :: mdio_clause [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_mdio_clause_MASK      0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_mdio_clause_SHIFT     0
#define BCHP_UNIMAC_INTERFACE0_UNI3_MDIO_CFG_mdio_clause_DEFAULT   0x00000001

/***************************************************************************
 *RGMII_CTRL - RGMII Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: reserved0 [31:31] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved0_MASK      0x80000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved0_SHIFT     31

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: col_crs_mask [30:30] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_col_crs_mask_MASK   0x40000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_col_crs_mask_SHIFT  30
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_col_crs_mask_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: rx_err_mask [29:29] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rx_err_mask_MASK    0x20000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rx_err_mask_SHIFT   29
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rx_err_mask_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: rvmii_ref_sel [28:28] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rvmii_ref_sel_MASK  0x10000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rvmii_ref_sel_SHIFT 28
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rvmii_ref_sel_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: rgmii_cfg_port_mode [27:25] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_cfg_port_mode_MASK 0x0e000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_cfg_port_mode_SHIFT 25
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_cfg_port_mode_DEFAULT 0x00000003

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: rgmii_id_mode_disable [24:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_id_mode_disable_MASK 0x01000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_id_mode_disable_SHIFT 24
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_id_mode_disable_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: reserved1 [23:13] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved1_MASK      0x00ffe000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved1_SHIFT     13

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: lpi_count [12:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_lpi_count_MASK      0x00001f00
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_lpi_count_SHIFT     8
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_lpi_count_DEFAULT   0x0000000f

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: tx_clk_stop_en [07:07] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_tx_clk_stop_en_MASK 0x00000080
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_tx_clk_stop_en_SHIFT 7
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_tx_clk_stop_en_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: reserved2 [06:06] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved2_MASK      0x00000040
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved2_SHIFT     6

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: inband_en [05:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_inband_en_MASK      0x00000020
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_inband_en_SHIFT     5
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_inband_en_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: LINK [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_LINK_MASK           0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_LINK_SHIFT          4
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_LINK_DEFAULT        0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: reserved3 [03:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved3_MASK      0x0000000e
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_reserved3_SHIFT     1

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_CTRL :: rgmii_mode_en [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_mode_en_MASK  0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_mode_en_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_CTRL_rgmii_mode_en_DEFAULT 0x00000001

/***************************************************************************
 *RGMII_LED_CTRL - RGMII LED Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_LED_CTRL :: on_cycle_cnt [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_LED_CTRL_on_cycle_cnt_MASK 0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_LED_CTRL_on_cycle_cnt_SHIFT 16
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_LED_CTRL_on_cycle_cnt_DEFAULT 0x000003d4

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_LED_CTRL :: off_cycle_cnt [15:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_LED_CTRL_off_cycle_cnt_MASK 0x0000ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_LED_CTRL_off_cycle_cnt_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_LED_CTRL_off_cycle_cnt_DEFAULT 0x000003d4

/***************************************************************************
 *RX_TIME_STAMP - Receive Time Stamp Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RX_TIME_STAMP :: reserved0 [31:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RX_TIME_STAMP_reserved0_MASK   0xfffffffe
#define BCHP_UNIMAC_INTERFACE0_UNI3_RX_TIME_STAMP_reserved0_SHIFT  1

/* UNIMAC_INTERFACE0_UNI3 :: RX_TIME_STAMP :: Back_Pressure_Enable [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RX_TIME_STAMP_Back_Pressure_Enable_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_RX_TIME_STAMP_Back_Pressure_Enable_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RX_TIME_STAMP_Back_Pressure_Enable_DEFAULT 0x00000000

/***************************************************************************
 *MAC_STATUS - MAC Status Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: MAC_STATUS :: reserved0 [31:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_reserved0_MASK      0xffffffe0
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_reserved0_SHIFT     5

/* UNIMAC_INTERFACE0_UNI3 :: MAC_STATUS :: auto_config_en [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_auto_config_en_MASK 0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_auto_config_en_SHIFT 4

/* UNIMAC_INTERFACE0_UNI3 :: MAC_STATUS :: link_status [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_link_status_MASK    0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_link_status_SHIFT   3

/* UNIMAC_INTERFACE0_UNI3 :: MAC_STATUS :: Half_duplex [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_Half_duplex_MASK    0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_Half_duplex_SHIFT   2

/* UNIMAC_INTERFACE0_UNI3 :: MAC_STATUS :: Eth_Speed [01:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_Eth_Speed_MASK      0x00000003
#define BCHP_UNIMAC_INTERFACE0_UNI3_MAC_STATUS_Eth_Speed_SHIFT     0

/***************************************************************************
 *IRQ_STATUS - Interrupt Status Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: reserved0 [31:13] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_reserved0_MASK      0xffffe000
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_reserved0_SHIFT     13

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_LinkUp [12:12] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_LinkUp_MASK 0x00001000
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_LinkUp_SHIFT 12

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_LinkDown [11:11] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_LinkDown_MASK 0x00000800
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_LinkDown_SHIFT 11
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_LinkDown_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_PPP_Validated [10:10] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_PPP_Validated_MASK 0x00000400
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_PPP_Validated_SHIFT 10
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_PPP_Validated_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_Receive_Full [09:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Receive_Full_MASK 0x00000200
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Receive_Full_SHIFT 9
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Receive_Full_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_RUNT_Truncasted [08:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_RUNT_Truncasted_MASK 0x00000100
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_RUNT_Truncasted_SHIFT 8
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_RUNT_Truncasted_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_Frame_Truncasted [07:07] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Frame_Truncasted_MASK 0x00000080
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Frame_Truncasted_SHIFT 7
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Frame_Truncasted_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_Unicast [06:06] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Unicast_MASK 0x00000040
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Unicast_SHIFT 6
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Unicast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_VLAN [05:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_VLAN_MASK 0x00000020
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_VLAN_SHIFT 5
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_VLAN_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_Control [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Control_MASK 0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Control_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Control_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_BroadCast [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_BroadCast_MASK 0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_BroadCast_SHIFT 3
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_BroadCast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_Multicast [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Multicast_MASK 0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Multicast_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Multicast_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_CRC_Error [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_CRC_Error_MASK 0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_CRC_Error_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_CRC_Error_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: IRQ_STATUS :: Irq_Status_Receive_Error [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Receive_Error_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Receive_Error_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_IRQ_STATUS_Irq_Status_Receive_Error_DEFAULT 0x00000000

/***************************************************************************
 *PPP_STATUS - Priority Pause Packet Status Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: PPP_STATUS :: reserved0 [31:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_STATUS_reserved0_MASK      0xffffff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_STATUS_reserved0_SHIFT     8

/* UNIMAC_INTERFACE0_UNI3 :: PPP_STATUS :: PPP_Status [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_STATUS_PPP_Status_MASK     0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_STATUS_PPP_Status_SHIFT    0
#define BCHP_UNIMAC_INTERFACE0_UNI3_PPP_STATUS_PPP_Status_DEFAULT  0x00000000

/***************************************************************************
 *OVERFLOW_COUNTER - Receive Overflow Counter
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: OVERFLOW_COUNTER :: Overflow_Counter [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_OVERFLOW_COUNTER_Overflow_Counter_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_OVERFLOW_COUNTER_Overflow_Counter_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_OVERFLOW_COUNTER_Overflow_Counter_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_RX_CNTRL - RGMII ATE RX Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_CNTRL :: reserved0 [31:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_reserved0_MASK 0xff000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_reserved0_SHIFT 24

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_CNTRL :: ate_en [23:23] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_ate_en_MASK 0x00800000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_ate_en_SHIFT 23
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_ate_en_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_CNTRL :: good_count [22:18] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_good_count_MASK 0x007c0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_good_count_SHIFT 18
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_good_count_DEFAULT 0x00000004

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_CNTRL :: expected_data_1 [17:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_expected_data_1_MASK 0x0003fe00
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_expected_data_1_SHIFT 9
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_expected_data_1_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_CNTRL :: expected_data_0 [08:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_expected_data_0_MASK 0x000001ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_expected_data_0_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_CNTRL_expected_data_0_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_RX_STATUS - RGMII ATE RX Status Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_STATUS :: reserved0 [31:19] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_reserved0_MASK 0xfff80000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_reserved0_SHIFT 19

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_STATUS :: rx_ok [18:18] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_rx_ok_MASK 0x00040000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_rx_ok_SHIFT 18
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_rx_ok_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_STATUS :: received_data_1 [17:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_received_data_1_MASK 0x0003fe00
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_received_data_1_SHIFT 9
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_received_data_1_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_RX_STATUS :: received_data_0 [08:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_received_data_0_MASK 0x000001ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_received_data_0_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_RX_STATUS_received_data_0_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_TX_CNTRL_0 - RGMII ATE TX Control 0 Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_TX_CNTRL_0 :: reserved0 [31:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_reserved0_MASK 0xfffffffc
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_reserved0_SHIFT 2

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_TX_CNTRL_0 :: start_stop [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_start_stop_MASK 0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_start_stop_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_start_stop_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_TX_CNTRL_0 :: start_stop_ovrd [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_start_stop_ovrd_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_start_stop_ovrd_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_0_start_stop_ovrd_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_TX_CNTRL_1 - RGMII ATE TX Control 1 Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_TX_CNTRL_1 :: reserved0 [31:18] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_reserved0_MASK 0xfffc0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_reserved0_SHIFT 18

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_TX_CNTRL_1 :: tx_data_1 [17:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_tx_data_1_MASK 0x0003fe00
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_tx_data_1_SHIFT 9
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_tx_data_1_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_ATE_TX_CNTRL_1 :: tx_data_0 [08:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_tx_data_0_MASK 0x000001ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_tx_data_0_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_ATE_TX_CNTRL_1_tx_data_0_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_RX_CLOCK_DELAY_CNTRL - RGMII TX Clock Delay Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_RX_CLOCK_DELAY_CNTRL :: reserved0 [31:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_reserved0_MASK 0xffffff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_reserved0_SHIFT 8

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_RX_CLOCK_DELAY_CNTRL :: dly_override [07:07] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_dly_override_MASK 0x00000080
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_dly_override_SHIFT 7
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_dly_override_DEFAULT 0x00000001

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_RX_CLOCK_DELAY_CNTRL :: dly_sel [06:06] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_dly_sel_MASK 0x00000040
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_dly_sel_SHIFT 6
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_dly_sel_DEFAULT 0x00000001

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_RX_CLOCK_DELAY_CNTRL :: bypass [05:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_bypass_MASK 0x00000020
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_bypass_SHIFT 5
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_bypass_DEFAULT 0x00000001

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_RX_CLOCK_DELAY_CNTRL :: iddq [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_iddq_MASK 0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_iddq_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_iddq_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_RX_CLOCK_DELAY_CNTRL :: drng [03:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_drng_MASK 0x0000000c
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_drng_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_drng_DEFAULT 0x00000002

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_RX_CLOCK_DELAY_CNTRL :: ctri [01:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_ctri_MASK 0x00000003
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_ctri_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_RX_CLOCK_DELAY_CNTRL_ctri_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_IB_STATUS - RGMII In-band Status Delay Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: RGMII_IB_STATUS :: reserved0 [31:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_reserved0_MASK 0xfffffff0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_reserved0_SHIFT 4

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_IB_STATUS :: link_decode [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_link_decode_MASK 0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_link_decode_SHIFT 3
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_link_decode_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_IB_STATUS :: duplex_decode [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_duplex_decode_MASK 0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_duplex_decode_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_duplex_decode_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: RGMII_IB_STATUS :: speed_decode [01:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_speed_decode_MASK 0x00000003
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_speed_decode_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_RGMII_IB_STATUS_speed_decode_DEFAULT 0x00000000

/***************************************************************************
 *INTF_DIAG_OUT - Interface diagnostic read value
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: INTF_DIAG_OUT :: Diag_Out [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_INTF_DIAG_OUT_Diag_Out_MASK    0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_INTF_DIAG_OUT_Diag_Out_SHIFT   0

/***************************************************************************
 *UNIMAC_STATUS - Unimac Core Status
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: UNIMAC_STATUS :: reserved0 [31:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_reserved0_MASK   0xffffffe0
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_reserved0_SHIFT  5

/* UNIMAC_INTERFACE0_UNI3 :: UNIMAC_STATUS :: MAC_TX_FULL [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_MAC_TX_FULL_MASK 0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_MAC_TX_FULL_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_MAC_TX_FULL_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: UNIMAC_STATUS :: LPI_TX_DETECT [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_LPI_TX_DETECT_MASK 0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_LPI_TX_DETECT_SHIFT 3
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_LPI_TX_DETECT_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: UNIMAC_STATUS :: LPI_RX_DETECT [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_LPI_RX_DETECT_MASK 0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_LPI_RX_DETECT_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_LPI_RX_DETECT_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: UNIMAC_STATUS :: RX_FIFO_DATA_AVAILABLE [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_RX_FIFO_DATA_AVAILABLE_MASK 0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_RX_FIFO_DATA_AVAILABLE_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_RX_FIFO_DATA_AVAILABLE_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: UNIMAC_STATUS :: MAC_TX_PAUSE [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_MAC_TX_PAUSE_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_MAC_TX_PAUSE_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_UNIMAC_STATUS_MAC_TX_PAUSE_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_CONTROL - Time Stamp Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: reserved0 [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_reserved0_MASK 0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_reserved0_SHIFT 16

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Download_Synchronous_Timer [15:15] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_MASK 0x00008000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_SHIFT 15
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: reserved1 [14:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_reserved1_MASK 0x00007f00
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_reserved1_SHIFT 8

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Clear_Timer [07:07] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Clear_Timer_MASK 0x00000080
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Clear_Timer_SHIFT 7
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Clear_Timer_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Snap_Shot_Timer [06:06] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Snap_Shot_Timer_MASK 0x00000040
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Snap_Shot_Timer_SHIFT 6
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Snap_Shot_Timer_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Download_Synchronous_Timer_Slot [05:05] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Slot_MASK 0x00000020
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Slot_SHIFT 5
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Slot_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Download_Synchronous_Timer_Freq_Adjust [04:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Freq_Adjust_MASK 0x00000010
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Freq_Adjust_SHIFT 4
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Freq_Adjust_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Download_Synchronous_Timer_Phase_Adjust [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Phase_Adjust_MASK 0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Phase_Adjust_SHIFT 3
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Phase_Adjust_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Download_Synchronous_Timer_Value [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Value_MASK 0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Value_SHIFT 2
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Synchronous_Timer_Value_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Download_FreeRunning_Timer_Value [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_FreeRunning_Timer_Value_MASK 0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_FreeRunning_Timer_Value_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_FreeRunning_Timer_Value_DEFAULT 0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_CONTROL :: Download_Timer_Control [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Timer_Control_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Timer_Control_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_CONTROL_Download_Timer_Control_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_MODE - Time Stamp Sync Mode Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_MODE :: reserved0 [31:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_MODE_reserved0_MASK 0xfffffffc
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_MODE_reserved0_SHIFT 2

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_MODE :: Sync_Mode [01:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_MODE_Sync_Mode_MASK 0x00000003
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_MODE_Sync_Mode_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_MODE_Sync_Mode_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_INCREMENT - Time Stamp Increment Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_INCREMENT :: Increment [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_INCREMENT_Increment_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_INCREMENT_Increment_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_INCREMENT_Increment_DEFAULT 0x00000005

/***************************************************************************
 *TIME_STAMP_PHASE_STEP - Time Stamp Phase Step Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_PHASE_STEP :: Phase_Step [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_STEP_Phase_Step_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_STEP_Phase_Step_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_STEP_Phase_Step_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_PHASE_DURATION - Time Stamp Phase Duration Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_PHASE_DURATION :: reserved0 [31:15] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_DURATION_reserved0_MASK 0xffff8000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_DURATION_reserved0_SHIFT 15

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_PHASE_DURATION :: Phase_Duration [14:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_DURATION_Phase_Duration_MASK 0x00007fff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_DURATION_Phase_Duration_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_PHASE_DURATION_Phase_Duration_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_FREQUENCY_STEP - Time Stamp Frequency Step Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_FREQUENCY_STEP :: Frequency_Step [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_STEP_Frequency_Step_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_STEP_Frequency_Step_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_STEP_Frequency_Step_DEFAULT 0x00000006

/***************************************************************************
 *TIME_STAMP_FREQUENCY_PERIOD - Time Stamp Frequency Period Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_FREQUENCY_PERIOD :: reserved0 [31:20] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_PERIOD_reserved0_MASK 0xfff00000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_PERIOD_reserved0_SHIFT 20

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_FREQUENCY_PERIOD :: Frequency_Period [19:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_PERIOD_Frequency_Period_MASK 0x000fffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_PERIOD_Frequency_Period_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREQUENCY_PERIOD_Frequency_Period_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_ROLL_OVER - Time Stamp Roll Over Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_ROLL_OVER :: Roll_over [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_ROLL_OVER_Roll_over_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_ROLL_OVER_Roll_over_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_ROLL_OVER_Roll_over_DEFAULT 0x3b9aca00

/***************************************************************************
 *TIME_STAMP_FREE_RUNNING_TIMER_LOCAL - Time Stamp Free Running Timer Local Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_FREE_RUNNING_TIMER_LOCAL :: Free_Running_Timer_Local [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_TIMER_LOCAL_Free_Running_Timer_Local_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_TIMER_LOCAL_Free_Running_Timer_Local_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_TIMER_LOCAL_Free_Running_Timer_Local_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_FREE_RUNNING_SECOND - Time Stamp Free Running Second Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_FREE_RUNNING_SECOND :: Free_Running_Second [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_SECOND_Free_Running_Second_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_SECOND_Free_Running_Second_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_SECOND_Free_Running_Second_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_FREE_RUNNING_EPOCH - Time Stamp Free Running Epoch Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_FREE_RUNNING_EPOCH :: reserved0 [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_EPOCH_reserved0_MASK 0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_EPOCH_reserved0_SHIFT 16

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_FREE_RUNNING_EPOCH :: Free_Running_Epoch [15:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_EPOCH_Free_Running_Epoch_MASK 0x0000ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_EPOCH_Free_Running_Epoch_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_FREE_RUNNING_EPOCH_Free_Running_Epoch_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_TIMER_LOCAL - Time Stamp Synchronous Timer Local Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_TIMER_LOCAL :: Synchronous_Timer_Local [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_LOCAL_Synchronous_Timer_Local_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_LOCAL_Synchronous_Timer_Local_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_LOCAL_Synchronous_Timer_Local_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_SECOND - Time Stamp Synchronous Second Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_SECOND :: Synchronous_Second [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SECOND_Synchronous_Second_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SECOND_Synchronous_Second_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SECOND_Synchronous_Second_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_EPOCH - Time Stamp Synchronous Epoch Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_EPOCH :: reserved0 [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_EPOCH_reserved0_MASK 0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_EPOCH_reserved0_SHIFT 16

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_EPOCH :: Synchronous_Epoch [15:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_EPOCH_Synchronous_Epoch_MASK 0x0000ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_EPOCH_Synchronous_Epoch_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_EPOCH_Synchronous_Epoch_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_EPOCH_CNT - Time Stamp Epoch Count Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_EPOCH_CNT :: Synchronous_Epoch [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_EPOCH_CNT_Synchronous_Epoch_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_EPOCH_CNT_Synchronous_Epoch_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_EPOCH_CNT_Synchronous_Epoch_DEFAULT 0xffffffff

/***************************************************************************
 *TIME_STAMP_SNAP_SHOT_FREE_RUNNING_TIMER_LOCAL - Time Stamp Snap Shot Free Running Timer Local Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_FREE_RUNNING_TIMER_LOCAL :: Snap_Shot_Free_Running_Timer_Local [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_TIMER_LOCAL_Snap_Shot_Free_Running_Timer_Local_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_TIMER_LOCAL_Snap_Shot_Free_Running_Timer_Local_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_TIMER_LOCAL_Snap_Shot_Free_Running_Timer_Local_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SNAP_SHOT_FREE_RUNNING_SECOND - Time Stamp Snap Shot Free Running Second Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_FREE_RUNNING_SECOND :: Snap_Shot_Free_Running_Second [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_SECOND_Snap_Shot_Free_Running_Second_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_SECOND_Snap_Shot_Free_Running_Second_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_SECOND_Snap_Shot_Free_Running_Second_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH - Time Stamp Snap Shot Free Running Epoch Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH :: reserved0 [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH_reserved0_MASK 0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH_reserved0_SHIFT 16

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH :: Snap_Shot_Free_Running_Epoch [15:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH_Snap_Shot_Free_Running_Epoch_MASK 0x0000ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH_Snap_Shot_Free_Running_Epoch_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_FREE_RUNNING_EPOCH_Snap_Shot_Free_Running_Epoch_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SNAP_SHOT_SYNC_TIMER_LOCAL - Time Stamp Snap Shot Synchronous Timer Local Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_SYNC_TIMER_LOCAL :: Snap_Shot_Synchronous_Timer_Local [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_TIMER_LOCAL_Snap_Shot_Synchronous_Timer_Local_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_TIMER_LOCAL_Snap_Shot_Synchronous_Timer_Local_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_TIMER_LOCAL_Snap_Shot_Synchronous_Timer_Local_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SNAP_SHOT_SYNC_SECOND - Time Stamp Snap Shot Synchronous Second Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_SYNC_SECOND :: Snap_Shot_Synchronous_Second [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_SECOND_Snap_Shot_Synchronous_Second_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_SECOND_Snap_Shot_Synchronous_Second_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_SECOND_Snap_Shot_Synchronous_Second_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SNAP_SHOT_SYNC_EPOCH - Time Stamp Snap Shot Synchronous Epoch Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_SYNC_EPOCH :: reserved0 [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_EPOCH_reserved0_MASK 0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_EPOCH_reserved0_SHIFT 16

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SNAP_SHOT_SYNC_EPOCH :: Snap_Shot_Synchronous_Epoch [15:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_EPOCH_Snap_Shot_Synchronous_Epoch_MASK 0x0000ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_EPOCH_Snap_Shot_Synchronous_Epoch_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SNAP_SHOT_SYNC_EPOCH_Snap_Shot_Synchronous_Epoch_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_TIMER_SLOT - Time Stamp Synchronous Timer Slot Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_TIMER_SLOT :: reserved0 [31:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_SLOT_reserved0_MASK 0xffffff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_SLOT_reserved0_SHIFT 8

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_TIMER_SLOT :: Synchronous_Slot [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_SLOT_Synchronous_Slot_MASK 0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_SLOT_Synchronous_Slot_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_TIMER_SLOT_Synchronous_Slot_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_SLOT_BASE - Time Stamp Synchronous Slot And Base Timer Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_SLOT_BASE :: Synchronous_Slot_Base [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SLOT_BASE_Synchronous_Slot_Base_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SLOT_BASE_Synchronous_Slot_Base_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_SLOT_BASE_Synchronous_Slot_Base_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_PCR - Time Stamp Synchronous PCR Timer Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_PCR :: Synchronous_PCR [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_PCR_Synchronous_PCR_MASK 0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_PCR_Synchronous_PCR_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_PCR_Synchronous_PCR_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_SYNC_WAIT_THRESHOLD - Time Stamp Synchronous Wait Threshold Timer Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_WAIT_THRESHOLD :: reserved0 [31:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_WAIT_THRESHOLD_reserved0_MASK 0xffffff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_WAIT_THRESHOLD_reserved0_SHIFT 8

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_SYNC_WAIT_THRESHOLD :: Wait_Threshold [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_WAIT_THRESHOLD_Wait_Threshold_MASK 0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_WAIT_THRESHOLD_Wait_Threshold_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_SYNC_WAIT_THRESHOLD_Wait_Threshold_DEFAULT 0x00000000

/***************************************************************************
 *TIME_STAMP_DISABLE - Time Stamp Disable Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_DISABLE :: reserved0 [31:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_reserved0_MASK 0xfffffffc
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_reserved0_SHIFT 2

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_DISABLE :: Disable_Free_Running_Timer [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_Disable_Free_Running_Timer_MASK 0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_Disable_Free_Running_Timer_SHIFT 1
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_Disable_Free_Running_Timer_DEFAULT 0x00000001

/* UNIMAC_INTERFACE0_UNI3 :: TIME_STAMP_DISABLE :: Disable_Sync_Timer [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_Disable_Sync_Timer_MASK 0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_Disable_Sync_Timer_SHIFT 0
#define BCHP_UNIMAC_INTERFACE0_UNI3_TIME_STAMP_DISABLE_Disable_Sync_Timer_DEFAULT 0x00000001

/***************************************************************************
 *MPD_CTRL - Magic Packet Control Registers
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: MPD_CTRL :: reserved0 [31:28] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_reserved0_MASK        0xf0000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_reserved0_SHIFT       28

/* UNIMAC_INTERFACE0_UNI3 :: MPD_CTRL :: PSW_EN [27:27] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_PSW_EN_MASK           0x08000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_PSW_EN_SHIFT          27
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_PSW_EN_DEFAULT        0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: MPD_CTRL :: reserved1 [26:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_reserved1_MASK        0x07000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_reserved1_SHIFT       24

/* UNIMAC_INTERFACE0_UNI3 :: MPD_CTRL :: MSEQ_LEN [23:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_MSEQ_LEN_MASK         0x00ff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_MSEQ_LEN_SHIFT        16
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_MSEQ_LEN_DEFAULT      0x00000010

/* UNIMAC_INTERFACE0_UNI3 :: MPD_CTRL :: reserved2 [15:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_reserved2_MASK        0x0000fffe
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_reserved2_SHIFT       1

/* UNIMAC_INTERFACE0_UNI3 :: MPD_CTRL :: MPD_EN [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_MPD_EN_MASK           0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_MPD_EN_SHIFT          0
#define BCHP_UNIMAC_INTERFACE0_UNI3_MPD_CTRL_MPD_EN_DEFAULT        0x00000000

/***************************************************************************
 *PSW_MS - Magic Packet Optional password byte 0 and 1
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: PSW_MS :: reserved0 [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_MS_reserved0_MASK          0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_MS_reserved0_SHIFT         16

/* UNIMAC_INTERFACE0_UNI3 :: PSW_MS :: PSW_47_32 [15:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_MS_PSW_47_32_MASK          0x0000ffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_MS_PSW_47_32_SHIFT         0
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_MS_PSW_47_32_DEFAULT       0x00000000

/***************************************************************************
 *PSW_LS - Magic Packet Optional password byte 2 ~ 5
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: PSW_LS :: PSW_31_0 [31:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_LS_PSW_31_0_MASK           0xffffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_LS_PSW_31_0_SHIFT          0
#define BCHP_UNIMAC_INTERFACE0_UNI3_PSW_LS_PSW_31_0_DEFAULT        0x00000000

/***************************************************************************
 *CNTRL - HFB Control Register
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: CNTRL :: filter_en [31:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_filter_en_MASK           0xffff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_filter_en_SHIFT          16

/* UNIMAC_INTERFACE0_UNI3 :: CNTRL :: reserved0 [15:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_reserved0_MASK           0x0000fff8
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_reserved0_SHIFT          3

/* UNIMAC_INTERFACE0_UNI3 :: CNTRL :: acpi_en [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_acpi_en_MASK             0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_acpi_en_SHIFT            2
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_acpi_en_DEFAULT          0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: CNTRL :: Byte256_mode [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_Byte256_mode_MASK        0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_Byte256_mode_SHIFT       1
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_Byte256_mode_DEFAULT     0x00000001

/* UNIMAC_INTERFACE0_UNI3 :: CNTRL :: hfb_en [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_hfb_en_MASK              0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_hfb_en_SHIFT             0
#define BCHP_UNIMAC_INTERFACE0_UNI3_CNTRL_hfb_en_DEFAULT           0x00000000

/***************************************************************************
 *FLTR_LEN_0 - HFB Filter Length Register 0
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_0 :: filt3_len [31:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt3_len_MASK      0xff000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt3_len_SHIFT     24
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt3_len_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_0 :: filt2_len [23:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt2_len_MASK      0x00ff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt2_len_SHIFT     16
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt2_len_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_0 :: filt1_len [15:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt1_len_MASK      0x0000ff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt1_len_SHIFT     8
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt1_len_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_0 :: filt0_len [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt0_len_MASK      0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt0_len_SHIFT     0
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_0_filt0_len_DEFAULT   0x00000000

/***************************************************************************
 *FLTR_LEN_1 - HFB Filter Length Register 1
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_1 :: filt7_len [31:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt7_len_MASK      0xff000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt7_len_SHIFT     24
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt7_len_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_1 :: filt6_len [23:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt6_len_MASK      0x00ff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt6_len_SHIFT     16
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt6_len_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_1 :: filt5_len [15:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt5_len_MASK      0x0000ff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt5_len_SHIFT     8
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt5_len_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_1 :: filt4_len [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt4_len_MASK      0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt4_len_SHIFT     0
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_1_filt4_len_DEFAULT   0x00000000

/***************************************************************************
 *FLTR_LEN_2 - HFB Filter Length Register 2
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_2 :: filt11_len [31:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt11_len_MASK     0xff000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt11_len_SHIFT    24
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt11_len_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_2 :: filt10_len [23:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt10_len_MASK     0x00ff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt10_len_SHIFT    16
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt10_len_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_2 :: filt9_len [15:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt9_len_MASK      0x0000ff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt9_len_SHIFT     8
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt9_len_DEFAULT   0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_2 :: filt8_len [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt8_len_MASK      0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt8_len_SHIFT     0
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_2_filt8_len_DEFAULT   0x00000000

/***************************************************************************
 *FLTR_LEN_3 - HFB Filter Length Register 3
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_3 :: filt15_len [31:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt15_len_MASK     0xff000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt15_len_SHIFT    24
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt15_len_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_3 :: filt14_len [23:16] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt14_len_MASK     0x00ff0000
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt14_len_SHIFT    16
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt14_len_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_3 :: filt13_len [15:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt13_len_MASK     0x0000ff00
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt13_len_SHIFT    8
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt13_len_DEFAULT  0x00000000

/* UNIMAC_INTERFACE0_UNI3 :: FLTR_LEN_3 :: filt12_len [07:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt12_len_MASK     0x000000ff
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt12_len_SHIFT    0
#define BCHP_UNIMAC_INTERFACE0_UNI3_FLTR_LEN_3_filt12_len_DEFAULT  0x00000000

/***************************************************************************
 *WOL_STATUS - Wake-on-LAN status
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: reserved0 [31:12] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_reserved0_MASK      0xfffff000
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_reserved0_SHIFT     12

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: hfb_m_match_irq [11:11] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_m_match_irq_MASK 0x00000800
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_m_match_irq_SHIFT 11

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: hfb_s_match_irq [10:10] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_s_match_irq_MASK 0x00000400
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_s_match_irq_SHIFT 10

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: mpd_irq [09:09] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_mpd_irq_MASK        0x00000200
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_mpd_irq_SHIFT       9

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: wol_mode [08:08] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_wol_mode_MASK       0x00000100
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_wol_mode_SHIFT      8

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: reserved1 [07:04] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_reserved1_MASK      0x000000f0
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_reserved1_SHIFT     4

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: hfb_acpi_en [03:03] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_acpi_en_MASK    0x00000008
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_acpi_en_SHIFT   3

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: hfb_256b_mode [02:02] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_256b_mode_MASK  0x00000004
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_256b_mode_SHIFT 2

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: hfb_en [01:01] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_en_MASK         0x00000002
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_hfb_en_SHIFT        1

/* UNIMAC_INTERFACE0_UNI3 :: WOL_STATUS :: mpd_en [00:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_mpd_en_MASK         0x00000001
#define BCHP_UNIMAC_INTERFACE0_UNI3_WOL_STATUS_mpd_en_SHIFT        0

/***************************************************************************
 *PWR_CTRL - Power Control - controls for switching to low frequency device clock
 ***************************************************************************/
/* UNIMAC_INTERFACE0_UNI3 :: PWR_CTRL :: reserved0 [31:24] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PWR_CTRL_reserved0_MASK        0xff000000
#define BCHP_UNIMAC_INTERFACE0_UNI3_PWR_CTRL_reserved0_SHIFT       24

/* UNIMAC_INTERFACE0_UNI3 :: PWR_CTRL :: low_power_delay [23:00] */
#define BCHP_UNIMAC_INTERFACE0_UNI3_PWR_CTRL_low_power_delay_MASK  0x00ffffff
#define BCHP_UNIMAC_INTERFACE0_UNI3_PWR_CTRL_low_power_delay_SHIFT 0

#endif /* #ifndef BCHP_UNIMAC_INTERFACE0_UNI3_H__ */

/* End of File */
