/****************************************************************************
 *
 * Broadcom Proprietary and Confidential.
 * (c) 2017 Broadcom. All rights reserved.
 * The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 * Unless you and Broadcom execute a separate written software license
 * agreement governing use of this software, this software is licensed to
 * you under the terms of the GNU General Public License version 2 (the
 * "GPL"), available at [http://www.broadcom.com/licenses/GPLv2.php], with
 * the following added to such license:
 *
 * As a special exception, the copyright holders of this software give you
 * permission to link this software with independent modules, and to copy
 * and distribute the resulting executable under terms of your choice,
 * provided that you also meet, for each linked independent module, the
 * terms and conditions of the license of that module. An independent
 * module is a module which is not derived from this software. The special
 * exception does not apply to any modifications of the software.
 *
 * Notwithstanding the above, under no circumstances may you combine this
 * software in any way with any other Broadcom software provided under a
 * license other than the GPL, without Broadcom's express prior written
 * consent.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Wed Jun 10 03:09:39 2015
 *                 Full Compile MD5 Checksum  e8bde4108283f67d401938287dbb6bde
 *                     (minus title and desc)
 *                 MD5 Checksum               56f0f944fbd407545cd964e7b4e7f7b0
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_FPM_POOL_1_FPM_H__
#define BCHP_FPM_POOL_1_FPM_H__

/***************************************************************************
 *FPM_POOL_1_FPM - FPM Pool Management Registers
 ***************************************************************************/
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC  0x03a00600 /* [RW] POOL1 Allocation & De-allocation/Free Management Register */
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC  0x03a00608 /* [RW] POOL2 Allocation & De-allocation/Free Management Register */
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC  0x03a00610 /* [RW] POOL3 Allocation & De-allocation/Free Management Register */
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC  0x03a00618 /* [RW] POOL4 Allocation & De-allocation/Free Management Register */
#define BCHP_FPM_POOL_1_FPM_SPARE                0x03a00620 /* [RW] Spare Register for future use */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI           0x03a00624 /* [RW] Multi-cast Token Update Control Register */

/***************************************************************************
 *POOL1_ALLOC_DEALLOC - POOL1 Allocation & De-allocation/Free Management Register
 ***************************************************************************/
/* FPM_POOL_1_FPM :: POOL1_ALLOC_DEALLOC :: TOKEN_VALID [31:31] */
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_VALID_MASK   0x80000000
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_VALID_SHIFT  31
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_VALID_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL1_ALLOC_DEALLOC :: reserved0 [30:30] */
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_reserved0_MASK     0x40000000
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_reserved0_SHIFT    30

/* FPM_POOL_1_FPM :: POOL1_ALLOC_DEALLOC :: DDR [29:29] */
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_DDR_MASK           0x20000000
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_DDR_SHIFT          29
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_DDR_DEFAULT        0x00000000

/* FPM_POOL_1_FPM :: POOL1_ALLOC_DEALLOC :: TOKEN_INDEX [28:12] */
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_INDEX_MASK   0x1ffff000
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_INDEX_SHIFT  12
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_INDEX_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL1_ALLOC_DEALLOC :: TOKEN_SIZE [11:00] */
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_SIZE_MASK    0x00000fff
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_SIZE_SHIFT   0
#define BCHP_FPM_POOL_1_FPM_POOL1_ALLOC_DEALLOC_TOKEN_SIZE_DEFAULT 0x00000000

/***************************************************************************
 *POOL2_ALLOC_DEALLOC - POOL2 Allocation & De-allocation/Free Management Register
 ***************************************************************************/
/* FPM_POOL_1_FPM :: POOL2_ALLOC_DEALLOC :: TOKEN_VALID [31:31] */
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_VALID_MASK   0x80000000
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_VALID_SHIFT  31
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_VALID_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL2_ALLOC_DEALLOC :: reserved0 [30:30] */
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_reserved0_MASK     0x40000000
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_reserved0_SHIFT    30

/* FPM_POOL_1_FPM :: POOL2_ALLOC_DEALLOC :: DDR [29:29] */
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_DDR_MASK           0x20000000
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_DDR_SHIFT          29
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_DDR_DEFAULT        0x00000000

/* FPM_POOL_1_FPM :: POOL2_ALLOC_DEALLOC :: TOKEN_INDEX [28:12] */
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_INDEX_MASK   0x1ffff000
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_INDEX_SHIFT  12
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_INDEX_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL2_ALLOC_DEALLOC :: TOKEN_SIZE [11:00] */
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_SIZE_MASK    0x00000fff
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_SIZE_SHIFT   0
#define BCHP_FPM_POOL_1_FPM_POOL2_ALLOC_DEALLOC_TOKEN_SIZE_DEFAULT 0x00000000

/***************************************************************************
 *POOL3_ALLOC_DEALLOC - POOL3 Allocation & De-allocation/Free Management Register
 ***************************************************************************/
/* FPM_POOL_1_FPM :: POOL3_ALLOC_DEALLOC :: TOKEN_VALID [31:31] */
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_VALID_MASK   0x80000000
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_VALID_SHIFT  31
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_VALID_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL3_ALLOC_DEALLOC :: reserved0 [30:30] */
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_reserved0_MASK     0x40000000
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_reserved0_SHIFT    30

/* FPM_POOL_1_FPM :: POOL3_ALLOC_DEALLOC :: DDR [29:29] */
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_DDR_MASK           0x20000000
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_DDR_SHIFT          29
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_DDR_DEFAULT        0x00000000

/* FPM_POOL_1_FPM :: POOL3_ALLOC_DEALLOC :: TOKEN_INDEX [28:12] */
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_INDEX_MASK   0x1ffff000
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_INDEX_SHIFT  12
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_INDEX_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL3_ALLOC_DEALLOC :: TOKEN_SIZE [11:00] */
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_SIZE_MASK    0x00000fff
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_SIZE_SHIFT   0
#define BCHP_FPM_POOL_1_FPM_POOL3_ALLOC_DEALLOC_TOKEN_SIZE_DEFAULT 0x00000000

/***************************************************************************
 *POOL4_ALLOC_DEALLOC - POOL4 Allocation & De-allocation/Free Management Register
 ***************************************************************************/
/* FPM_POOL_1_FPM :: POOL4_ALLOC_DEALLOC :: TOKEN_VALID [31:31] */
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_VALID_MASK   0x80000000
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_VALID_SHIFT  31
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_VALID_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL4_ALLOC_DEALLOC :: reserved0 [30:30] */
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_reserved0_MASK     0x40000000
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_reserved0_SHIFT    30

/* FPM_POOL_1_FPM :: POOL4_ALLOC_DEALLOC :: DDR [29:29] */
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_DDR_MASK           0x20000000
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_DDR_SHIFT          29
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_DDR_DEFAULT        0x00000000

/* FPM_POOL_1_FPM :: POOL4_ALLOC_DEALLOC :: TOKEN_INDEX [28:12] */
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_INDEX_MASK   0x1ffff000
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_INDEX_SHIFT  12
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_INDEX_DEFAULT 0x00000000

/* FPM_POOL_1_FPM :: POOL4_ALLOC_DEALLOC :: TOKEN_SIZE [11:00] */
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_SIZE_MASK    0x00000fff
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_SIZE_SHIFT   0
#define BCHP_FPM_POOL_1_FPM_POOL4_ALLOC_DEALLOC_TOKEN_SIZE_DEFAULT 0x00000000

/***************************************************************************
 *SPARE - Spare Register for future use
 ***************************************************************************/
/* FPM_POOL_1_FPM :: SPARE :: SPARE_BITS [31:00] */
#define BCHP_FPM_POOL_1_FPM_SPARE_SPARE_BITS_MASK                  0xffffffff
#define BCHP_FPM_POOL_1_FPM_SPARE_SPARE_BITS_SHIFT                 0
#define BCHP_FPM_POOL_1_FPM_SPARE_SPARE_BITS_DEFAULT               0x00000000

/***************************************************************************
 *POOL_MULTI - Multi-cast Token Update Control Register
 ***************************************************************************/
/* FPM_POOL_1_FPM :: POOL_MULTI :: TOKEN_VALID [31:31] */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_VALID_MASK            0x80000000
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_VALID_SHIFT           31
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_VALID_DEFAULT         0x00000000

/* FPM_POOL_1_FPM :: POOL_MULTI :: reserved0 [30:30] */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_reserved0_MASK              0x40000000
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_reserved0_SHIFT             30

/* FPM_POOL_1_FPM :: POOL_MULTI :: DDR [29:29] */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_DDR_MASK                    0x20000000
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_DDR_SHIFT                   29
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_DDR_DEFAULT                 0x00000000

/* FPM_POOL_1_FPM :: POOL_MULTI :: TOKEN_INDEX [28:12] */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_INDEX_MASK            0x1ffff000
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_INDEX_SHIFT           12
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_INDEX_DEFAULT         0x00000000

/* FPM_POOL_1_FPM :: POOL_MULTI :: UPDATE_TYPE [11:11] */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_UPDATE_TYPE_MASK            0x00000800
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_UPDATE_TYPE_SHIFT           11
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_UPDATE_TYPE_DEFAULT         0x00000000

/* FPM_POOL_1_FPM :: POOL_MULTI :: reserved1 [10:07] */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_reserved1_MASK              0x00000780
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_reserved1_SHIFT             7

/* FPM_POOL_1_FPM :: POOL_MULTI :: TOKEN_MULTI [06:00] */
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_MULTI_MASK            0x0000007f
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_MULTI_SHIFT           0
#define BCHP_FPM_POOL_1_FPM_POOL_MULTI_TOKEN_MULTI_DEFAULT         0x00000000

#endif /* #ifndef BCHP_FPM_POOL_1_FPM_H__ */

/* End of File */
